"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

// Define available languages
export type Language = "en" | "ru" | "uz"

// Define translations interface
interface Translations {
  [key: string]: {
    [key: string]: string
  }
}

// Define the context type
interface AdminLanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
  isReady: boolean
}

// Default translations for admin panel
const defaultTranslations: Translations = {
  en: {
    // Dashboard
    dashboard: "Dashboard",
    totalUsers: "Total Users",
    totalCourses: "Total Courses",
    monthlyIncome: "Monthly Income",
    activeStudents: "Active Students",
    recentRegistrations: "Recent Registrations",
    recentPurchases: "Recent Purchases",
    comparedToLastMonth: "compared to last month",

    // Navigation
    users: "Users",
    courses: "Courses",
    teachers: "Teachers",
    jobs: "Jobs",
    schedule: "Schedule",
    chat: "Chat",
    analytics: "Analytics",
    reports: "Reports",
    settings: "Settings",
    website: "Website",
    help: "Help",
    logout: "Logout",
    backToSite: "Back to Site",
    viewSite: "View Site",

    // Language
    language: "Language",
    english: "English",
    russian: "Russian",
    uzbek: "Uzbek",

    // Theme
    darkMode: "Dark Mode",
    lightMode: "Light Mode",

    // General
    adminPanel: "Admin Panel",
    search: "Search",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    previous: "Previous",
    loading: "Loading...",
    noResults: "No results found",
    error: "Error",
    success: "Success",

    // Users
    userManagement: "User Management",
    addUser: "Add User",
    editUser: "Edit User",
    deleteUser: "Delete User",
    userName: "User Name",
    userEmail: "Email",
    userPhone: "Phone",
    userRole: "Role",
    userStatus: "Status",
    active: "Active",
    inactive: "Inactive",
    activate: "Activate",
    deactivate: "Deactivate",
    permissions: "Permissions",
    noPermission: "No Permission",
    noPermissionAddUsers: "You don't have permission to add users",
    requiredFieldsError: "Please fill in all required fields",
    userAdded: "User Added",
    userAddedSuccess: "User has been added successfully",
    addUserError: "Error Adding User",
    addUserErrorMessage: "There was an error adding the user",
    searchPlaceholder: "Search users...",
    registeredAt: "Registered At",
    actions: "Actions",
    allUsers: "All Users",
    manageAllUsers: "Manage all users in the system",

    // Courses
    courseManagement: "Course Management",
    addCourse: "Add Course",
    editCourse: "Edit Course",
    deleteCourse: "Delete Course",
    courseTitle: "Course Title",
    courseDescription: "Course Description",
    coursePrice: "Price",
    courseLevel: "Level",
    courseDuration: "Duration",
    courseStatus: "Status",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    allLevels: "All Levels",
    courseDetails: "Course Details",
    courseInformation: "Course Information",
    courseContent: "Course Content",
    courseTopics: "Course Topics",
    courseSettings: "Course Settings",
    course: "Course",
    instructor: "Instructor",
    lessons: "Lessons",
    students: "Students",
    rating: "Rating",
    createdAt: "Created At",
    updatedAt: "Updated At",
    view: "View",
    moreFilters: "More Filters",
    noCoursesFound: "No courses found",
    manageCoursesDescription: "Manage all courses in the system",
    searchCourses: "Search courses...",
    showing: "Showing",
    courses: "courses",
    totalCourses: "Total courses",
    perPage: "per page",
    deleteCourseConfirmation: "Are you sure you want to delete this course?",
    courseDeleted: "Course Deleted",
    courseDeletedSuccessfully: "Course has been deleted successfully",
    fillAllRequiredFields: "Please fill all required fields",
    errorSavingCourse: "Error saving course",
    courseAddedSuccessfully: "Course added successfully",
    newCourseAdded: "New Course Added",
    courseNowAvailable: "course is now available",
    enterCourseBasicInfo: "Enter basic information about the course",
    courseNamePlaceholder: "Enter course name",
    shortDescriptionPlaceholder: "Brief description of the course",
    detailedDescriptionPlaceholder: "Detailed description of what students will learn",
    selectLevel: "Select level",
    weeks: "weeks",
    instructorNamePlaceholder: "Instructor name",
    instructorPositionPlaceholder: "Instructor position or title",
    addModulesAndLessons: "Add modules and lessons for the course",
    moduleNamePlaceholder: "Module name",
    lessonNamePlaceholder: "Lesson name",
    lessonContentPlaceholder: "Lesson content or description",
    durationMinutes: "Duration (minutes)",
    videoUrlPlaceholder: "Video URL",
    enterMainTopicsCovered: "Enter main topics covered in the course",
    topicNamePlaceholder: "Topic name",
    addTestsAndMaterials: "Add tests and additional materials",
    tests: "Tests",
    addTest: "Add Test",
    addNewTest: "Add New Test",
    enterTestInfoAndQuestionCount: "Enter test information and number of questions",
    testName: "Test Name",
    testDescription: "Test Description",
    testDescriptionPlaceholder: "Description of what this test covers",
    questionCount: "Question Count",
    timeLimit: "Time Limit",
    minutes: "minutes",
    passingScore: "Passing Score",
    createTest: "Create Test",
    editTest: "Edit Test",
    editTestInfoAndQuestions: "Edit test information and questions",
    questions: "Questions",
    addQuestion: "Add Question",
    noQuestionsYet: "No questions yet",
    questionText: "Question Text",
    questionTextPlaceholder: "Enter the question",
    answerOptions: "Answer Options",
    addOption: "Add Option",
    answer: "Answer",
    correctAnswerExplanation: "Correct Answer Explanation",
    whyCorrectAnswerExplanation: "Explain why this is the correct answer",
    deleteQuestion: "Delete Question",
    noTestsYet: "No tests yet",
    additionalMaterials: "Additional Materials",
    addMaterial: "Add Material",
    materialNamePlaceholder: "Material name",
    fileType: "File Type",
    archive: "Archive",
    link: "Link",
    fileUrlOrLinkPlaceholder: "File URL or link",
    materialDescriptionPlaceholder: "Description of this material",
    noAdditionalMaterialsYet: "No additional materials yet",
    adjustAdditionalSettings: "Adjust additional settings for the course",
    isCourseVisibleToUsers: "Is this course visible to users?",

    // Teachers
    teacherManagement: "Teacher Management",
    addTeacher: "Add Teacher",
    editTeacher: "Edit Teacher",
    deleteTeacher: "Delete Teacher",
    teacherName: "Teacher Name",
    teacherEmail: "Email",
    teacherPhone: "Phone",
    teacherSpecialization: "Specialization",
    teacherCourses: "Courses",
    teachersList: "Teachers List",
    manageTeachers: "Manage Teachers",
    teacherPosition: "Position",
    teacherSpecialty: "Specialty",
    teacherExperience: "Experience",
    manageAllTeachers: "Manage all teachers in the system",
    addNewTeacher: "Add New Teacher",
    teacherInformation: "Teacher Information",
    fillAllTeacherInfo: "Fill in all teacher information",
    fullName: "Full Name",
    namePlaceholder: "Enter full name",
    email: "Email",
    emailPlaceholder: "Enter email address",
    phone: "Phone",
    phonePlaceholder: "Enter phone number",
    specialization: "Specialization",
    specializationPlaceholder: "Enter specialization",
    status: "Status",
    selectStatus: "Select status",
    noCourseAvailable: "No courses available",
    saving: "Saving...",
    teacherAdded: "Teacher Added",
    teacherAddedSuccess: "Teacher has been added successfully",
    teacherDeleted: "Teacher Deleted",
    teacherDeletedSuccess: "Teacher has been deleted successfully",
    teacherDeletedNotification: "has been removed from the teaching staff",
    confirmDeleteTeacher: "Confirm Delete Teacher",
    deleteTeacherWarning: "Are you sure you want to delete this teacher? This action cannot be undone.",
    searchTeachers: "Search teachers...",
    teacherLoadError: "Error Loading Teachers",
    teacherLoadErrorMessage: "There was an error loading teachers",
    newTeacher: "New Teacher",
    position: "Position",
    specialty: "Specialty",
    experience: "Experience",
    assignedCourses: "Assigned Courses",
    teacher: "Teacher",
    englishLanguage: "English Language",
    unknown: "Unknown",
    teacherBio: "is an experienced teacher",
    azizaBio: "Aziza is a senior English language teacher with extensive experience in teaching IT professionals",
    boburBio: "Bobur specializes in teaching English for IT professionals with focus on technical vocabulary",
    jasurBio: "Jasur is a senior web developer who teaches modern web technologies",
    dilshodBio: "Dilshod is a Python developer and instructor with focus on data science",
    malikaBio: "Malika is a Java developer and instructor with experience in enterprise applications",
    seniorEnglishTeacher: "Senior English Teacher",
    itEnglishSpecialist: "IT English Specialist",
    seniorWebDeveloper: "Senior Web Developer",
    pythonDeveloper: "Python Developer",
    javaDeveloper: "Java Developer",
    itEnglish: "IT English",
    webDevelopment: "Web Development",
    pythonProgramming: "Python Programming",
    javaProgramming: "Java Programming",
    years: "years",
    new: "New",
    noPermissionAddTeachers: "You don't have permission to add teachers",
    coursesLoadError: "Error loading courses",
    activeValue: "active",
    addTeacherError: "Error adding teacher",
    addTeacherErrorMessage: "There was an error adding the teacher",

    // Jobs
    jobManagement: "Job Management",
    addJob: "Add Job",
    editJob: "Edit Job",
    deleteJob: "Delete Job",
    jobTitle: "Job Title",
    jobCompany: "Company",
    jobLocation: "Location",
    jobType: "Job Type",
    jobSalary: "Salary",
    jobDescription: "Description",
    jobRequirements: "Requirements",
    jobsList: "Jobs List",
    manageJobs: "Manage Jobs",
    jobApplications: "Job Applications",
    newJobListing: "New Job Listing",
    jobListings: "Job Listings",
    applications: "Applications",
    position: "Position",
    company: "Company",
    location: "Location",
    salary: "Salary",
    status: "Status",
    applicationId: "Application ID",
    applicantName: "Applicant Name",
    dateSubmitted: "Date Submitted",
    viewApplication: "View Application",
    addNewJobListing: "Add New Job Listing",
    jobListingDetails: "Job Listing Details",
    fillFormToCreateNewJob: "Fill out the form to create a new job listing",
    positionName: "Position Name",
    positionNamePlaceholder: "e.g., Senior Frontend Developer",
    companyPlaceholder: "e.g., TechGlobal Inc.",
    locationPlaceholder: "e.g., Berlin, Germany",
    selectJobType: "Select job type",
    fullTime: "Full-time",
    partTime: "Part-time",
    contract: "Contract",
    remote: "Remote",
    salaryPlaceholder: "e.g., $80,000 - $100,000",
    jobDescriptionPlaceholder: "Detailed job description...",
    requirement: "Requirement",
    addRequirement: "Add Requirement",
    addJobListing: "Add Job Listing",
    jobAdded: "Job Added",
    jobAddedSuccess: "Job has been added successfully",
    requirementsError: "Please add at least one requirement",
    jobSaveError: "Error saving job",
    deleteJobListing: "Delete Job Listing",
    deleteJobConfirmation: "Are you sure you want to delete this job listing?",
    noJobListingsFound: "No job listings found",
    noJobListingsYet: "You haven't created any job listings yet",
    addFirstJobListing: "Add First Job Listing",
    searchApplications: "Search applications...",
    searchJobs: "Search jobs...",
    noApplicationsFound: "No applications found",
    noApplicationsYet: "No applications have been submitted yet",
    new: "New",
    reviewed: "Reviewed",
    interviewed: "Interviewed",
    accepted: "Accepted",
    rejected: "Rejected",

    // Application details
    applicationDetails: "Application Details",
    submittedDate: "Submitted Date",
    positionDetails: "Position Details",
    personalInformation: "Personal Information",
    motivationLetter: "Motivation Letter",
    documents: "Documents",
    resume: "Resume",
    passport: "Passport",
    diploma: "Diploma",
    certificates: "Certificates",
    download: "Download",
    statusNew: "New",
    statusReviewed: "Reviewed",
    statusInterviewed: "Interviewed",
    statusAccepted: "Accepted",
    statusRejected: "Rejected",
    statusUnknown: "Unknown",
    statusUpdated: "Status Updated",
    applicationStatusUpdatedSuccessfully: "Application status has been updated successfully",
    applicationNotFound: "Application not found",
    failedToLoadApplication: "Failed to load application data",
    failedToUpdateApplicationStatus: "Failed to update application status",
    applicationStatusUpdated: "Application Status Updated",
    yourApplicationFor: "Your application for",
    hasBeenUpdatedTo: "has been updated to",
    job: "job",

    // Logout
    logoutSuccess: "Logged Out",
    logoutSuccessMessage: "You have been successfully logged out",

    // Reports
    reports: "Reports",
    generateReport: "Generate Report",
    salesReport: "Sales Report",
    userReport: "User Report",
    courseReport: "Course Report",
    revenueByPaymentMethod: "Revenue by Payment Method",
    revenueByCourse: "Revenue by Course",
    monthlyRevenue: "Monthly Income",
    downloadReport: "Download Report",
    timeRange: "Time Range",
    lastWeek: "Last Week",
    lastMonth: "Last Month",
    lastYear: "Last Year",
    allTime: "All Time",
    downloadingReport: "Downloading Report",
    downloading: "downloading",
    totalRevenuePerCourse: "Total revenue per course",
    totalRevenuePerPaymentMethod: "Total revenue per payment method",
    monthlyRevenueForLast12Months: "Monthly revenue for last 12 months",
    userActivityInformation: "Information about user activity",
    currency: "som",

    // Settings
    systemSettings: "System Settings",
    generalSettings: "General Settings",
    notificationSettings: "Notification Settings",
    paymentSettings: "Payment Settings",
    securitySettings: "Security Settings",
    changeBasicInformationForSite: "Change basic information for the site",
    siteName: "Site Name",
    siteDescription: "Site Description",
    contactEmail: "Contact Email",
    contactPhone: "Contact Phone",
    address: "Address",
    settingsSaved: "Settings Saved",
    allSettingsSavedSuccessfully: "All settings were saved successfully",
    chooseNotificationsToReceive: "Choose which notifications you want to receive",
    emailNotifications: "Email Notifications",
    receiveSystemNotificationsViaEmail: "Receive system notifications via email",
    newUserNotifications: "New User Notifications",
    receiveNotificationWhenNewUserRegisters: "Receive notification when a new user registers",
    newOrderNotifications: "New Order Notifications",
    receiveNotificationWhenNewOrderPlaced: "Receive notification when a new order is placed",
    marketingEmails: "Marketing Emails",
    receiveMarketingAndNewsEmails: "Receive marketing and news emails",
    configurePaymentMethods: "Configure payment methods",
    bankTransfer: "Bank Transfer",
    bankDetails: "Bank Details",
    cash: "Cash",

    // Website
    websiteSettings: "Website Settings",
    homepageSettings: "Homepage Settings",
    socialMediaSettings: "Social Media Settings",
    mediaSettings: "Media Settings",
    websiteManagement: "Website Management",
    noPermissionWebsite: "You don't have permission to manage website settings. Please contact an administrator.",
    general: "General",
    homePage: "Home Page",
    socialMedia: "Social Media",
    media: "Media",
    configureHomepage: "Configure the homepage appearance",
    heroTitle: "Hero Title",
    heroDescription: "Hero Description",
    showFeaturedCourses: "Show Featured Courses",
    showFeaturedCoursesDescription: "Show featured courses section on the homepage",
    showTestimonials: "Show Testimonials",
    showTestimonialsDescription: "Show student testimonials section on the homepage",
    showPartners: "Show Partners",
    showPartnersDescription: "Show partners section on the homepage",
    configureSocialLinks: "Configure social media links",
    manageMediaFiles: "Manage media files for the website",
    mediaManagementComingSoon: "Media files management will be added soon",
    saving: "Saving...",

    // Help page translations
    helpAndSupport: "Help and Support",
    searchHelpPlaceholder: "Enter a question or keyword...",
    faqDescription: "Most frequently asked questions about the system",
    howToAddCourse: "How to add a new course?",
    howToAddCourseAnswer:
      "To add a new course, go to the 'Courses' section and click on the 'Add Course' button. Fill in all the required information and click 'Save'. The course will be added and can be edited or deleted later.",
    howToChangeUserPermissions: "How to change user permissions?",
    howToChangeUserPermissionsAnswer:
      "To change user permissions, go to the 'Users' section and select the user you want to modify. Click on the 'Edit' button and change the user's role or specific permissions. Save the changes to apply the new permissions.",
    howToDownloadReports: "How to download reports?",
    howToDownloadReportsAnswer:
      "To download reports, go to the 'Analytics' section and select the report type you want. Click on the 'Download Report' button and the report will be downloaded. Reports are available in Excel, PDF, and CSV formats.",
    whatToDoWhenError: "What to do when an error occurs?",
    whatToDoWhenErrorAnswer:
      "If an error occurs, first try refreshing your browser. If the problem persists, log out and log back in. If the issue continues, go to the 'Contact' section and provide information about the problem. Technical support will assist you.",
    howToChangeLanguage: "How to change the system language?",
    howToChangeLanguageAnswer:
      "To change the system language, click on the language selection button in the top right corner and select your preferred language. The system is available in three languages: Uzbek, Russian, and English.",

    // Guides section
    guides: "Guides",
    guidesDescription: "System usage guides",
    courseManagementGuide: "Course Management",
    courseManagementGuideDescription: "Guide for adding, editing, and deleting courses",
    userManagementGuide: "User Management",
    userManagementGuideDescription: "Guide for managing users and changing permissions",
    reportsGuide: "Working with Reports",
    reportsGuideDescription: "Guide for viewing and downloading reports",
    paymentsGuide: "Payment Management",
    paymentsGuideDescription: "Guide for tracking and managing payments",
    messagesGuide: "Message Management",
    messagesGuideDescription: "Guide for sending and receiving messages",
    systemSettingsGuide: "System Settings",
    systemSettingsGuideDescription: "Guide for changing system settings",
    viewGuide: "View Guide",

    // Contact support section
    contactSupport: "Contact Support",
    contactSupportDescription: "Contact technical support service",
    byEmail: "By Email",
    responseTime24Hours: "We will respond within 24 hours",
    byPhone: "By Phone",
    workingHours: "Working hours: 9:00 - 18:00",
    byChat: "By Chat",
    byChatDescription: "Contact us via online chat",
    forQuickResponse: "For quick response",
    yourName: "Your Name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    sendMessage: "Send Message",
    messageSent: "Message Sent",
    messageSuccessfullySent: "Your message has been sent successfully. We will respond soon.",

    // Help
    helpAndSupport: "Help and Support",
    faq: "FAQ",
    contactSupport: "Contact Support",
    documentation: "Documentation",

    // Confirmation
    confirmDelete: "Are you sure you want to delete this?",
    confirmDeleteDescription: "This action cannot be undone.",

    // Table
    id: "ID",
    name: "Name",
    email: "Email",
    phone: "Phone",
    role: "Role",
    status: "Status",
    actions: "Actions",

    // Pagination
    showing: "Showing",
    of: "of",
    items: "items",
    perPage: "per page",

    // Filters
    filter: "Filter",
    allStatuses: "All Statuses",
    planned: "Planned",
    archived: "Archived",

    // Time
    yesterday: "Yesterday",
    today: "Today",

    // Errors
    failedToLoadData: "Failed to load data",
    failedToSaveData: "Failed to save data",
    accessDenied: "Access Denied",

    // Success messages
    savedSuccessfully: "Saved successfully",
    deletedSuccessfully: "Deleted successfully",

    // Placeholders
    searchPlaceholder: "Search...",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Password",

    // Buttons
    signIn: "Sign In",
    signOut: "Sign Out",

    // Analytics page
    analytics: "Analytics",
    downloadReport: "Download Report",
    overview: "Overview",
    users: "Users",
    courses: "Courses",
    revenue: "Revenue",
    userStatistics: "User Statistics",
    courseStatistics: "Course Statistics",
    revenueStatistics: "Revenue Statistics",
    activityLast30Days: "Activity in the last 30 days",
    chartDataWillBeDisplayed: "Chart data will be displayed here",
    allTime: "All time",
    currentMonth: "Current month",
    average: "Average",

    // Schedule page translations
    scheduleManagement: "Schedule Management",
    weeklySchedule: "Weekly Schedule",
    addNewClass: "Add New Class",
    time: "Time",
    room: "Room",
    noClassesForDay: "No classes scheduled for this day",
    editSchedule: "Edit Schedule",
    addSchedule: "Add Schedule",
    day: "Day",
    selectDay: "Select day",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    noClassesScheduled: "No classes scheduled",
    lightTheme: "Light",
    darkTheme: "Dark",
    systemTheme: "System",
    toggleTheme: "Toggle theme",

    // Chat page translations
    supportChat: "Support Chat",
    chatWithStudents: "Chat with students and provide support",
    allChats: "All Chats",
    unread: "Unread",
    archived: "Archived",
    searchConversations: "Search conversations...",
    noConversationsFound: "No conversations found",
    online: "Online",
    selectConversation: "Select a Conversation",
    selectConversationDescription: "Choose a conversation from the list to start chatting",
    unreadMessages: "Unread Messages",
    unreadMessagesDescription: "Messages that haven't been read yet",
    archivedChats: "Archived Chats",
    archivedChatsDescription: "Conversations that have been archived",
    typeMessage: "Type a message...",
    send: "Send",
  },
  ru: {
    // Dashboard
    dashboard: "Панель управления",
    totalUsers: "Всего пользователей",
    totalCourses: "Всего курсов",
    monthlyIncome: "Ежемесячный доход",
    activeStudents: "Активные студенты",
    recentRegistrations: "Последние регистрации",
    recentPurchases: "Последние покупки",
    comparedToLastMonth: "по сравнению с прошлым месяцем",

    // Navigation
    users: "Пользователи",
    courses: "Курсы",
    teachers: "Преподаватели",
    jobs: "Вакансии",
    schedule: "Расписание",
    chat: "Чат",
    analytics: "Аналитика",
    reports: "Отчеты",
    settings: "Настройки",
    website: "Веб-сайт",
    help: "Помощь",
    logout: "Выход",
    backToSite: "Вернуться на сайт",
    viewSite: "Перейти на сайт",

    // Language
    language: "Язык",
    english: "Английский",
    russian: "Русский",
    uzbek: "Узбекский",

    // Theme
    darkMode: "Темный режим",
    lightMode: "Светлый режим",

    // General
    adminPanel: "Панель администратора",
    search: "Поиск",
    add: "Добавить",
    edit: "Редактировать",
    delete: "Удалить",
    save: "Сохранить",
    cancel: "Отмена",
    confirm: "Подтвердить",
    back: "Назад",
    next: "Далее",
    previous: "Предыдущий",
    loading: "Загрузка...",
    noResults: "Результаты не найдены",
    error: "Ошибка",
    success: "Успех",

    // Users
    userManagement: "Управление пользователями",
    addUser: "Добавить пользователя",
    editUser: "Редактировать пользователя",
    deleteUser: "Удалить пользователя",
    userName: "Имя пользователя",
    userEmail: "Email",
    userPhone: "Телефон",
    userRole: "Роль",
    userStatus: "Статус",
    active: "Активный",
    inactive: "Неактивный",
    activate: "Активировать",
    deactivate: "Деактивировать",
    permissions: "Разрешения",
    noPermission: "Нет разрешения",
    noPermissionAddUsers: "У вас нет разрешения на добавление пользователей",
    requiredFieldsError: "Пожалуйста, заполните все обязательные поля",
    userAdded: "Пользователь добавлен",
    userAddedSuccess: "Пользователь успешно добавлен",
    addUserError: "Ошибка добавления пользователя",
    addUserErrorMessage: "Произошла ошибка при добавлении пользователя",
    searchPlaceholder: "Поиск пользователей...",
    registeredAt: "Дата регистрации",
    actions: "Действия",
    allUsers: "Все пользователи",
    manageAllUsers: "Управление всеми пользователями в системе",

    // Courses
    courseManagement: "Управление курсами",
    addCourse: "Добавить курс",
    editCourse: "Редактировать курс",
    deleteCourse: "Удалить курс",
    courseTitle: "Название курса",
    courseDescription: "Описание курса",
    coursePrice: "Цена",
    courseLevel: "Уровень",
    courseDuration: "Продолжительность",
    courseStatus: "Статус",
    beginner: "Начинающий",
    intermediate: "Средний",
    advanced: "Продвинутый",
    allLevels: "Все уровни",
    courseDetails: "Детали курса",
    courseInformation: "Информация о курсе",
    courseContent: "Содержание курса",
    courseTopics: "Темы курса",
    courseSettings: "Настройки курса",
    course: "Курс",
    instructor: "Преподаватель",
    lessons: "Уроки",
    students: "Студенты",
    rating: "Рейтинг",
    createdAt: "Создано",
    updatedAt: "Обновлено",
    view: "Просмотр",
    moreFilters: "Больше фильтров",
    noCoursesFound: "Курсы не найдены",
    manageCoursesDescription: "Управление всеми курсами в системе",
    searchCourses: "Поиск курсов...",
    showing: "Показано",
    courses: "курсы",
    totalCourses: "Всего курсов",
    perPage: "на странице",
    deleteCourseConfirmation: "Вы уверены, что хотите удалить этот курс?",
    courseDeleted: "Курс удален",
    courseDeletedSuccessfully: "Курс успешно удален",
    fillAllRequiredFields: "Пожалуйста, заполните все обязательные поля",
    errorSavingCourse: "Ошибка сохранения курса",
    courseAddedSuccessfully: "Курс успешно добавлен",
    newCourseAdded: "Добавлен новый курс",
    courseNowAvailable: "курс теперь доступен",
    enterCourseBasicInfo: "Введите основную информацию о курсе",
    courseNamePlaceholder: "Введите название курса",
    shortDescriptionPlaceholder: "Краткое описание курса",
    detailedDescriptionPlaceholder: "Подробное описание того, что студенты изучат",
    selectLevel: "Выберите уровень",
    weeks: "недель",
    instructorNamePlaceholder: "Имя преподавателя",
    instructorPositionPlaceholder: "Должность или звание преподавателя",
    addModulesAndLessons: "Добавьте модули и уроки для курса",
    moduleNamePlaceholder: "Название модуля",
    lessonNamePlaceholder: "Название урока",
    lessonContentPlaceholder: "Содержание или описание урока",
    durationMinutes: "Продолжительность (минуты)",
    videoUrlPlaceholder: "URL видео",
    enterMainTopicsCovered: "Введите основные темы, охватываемые в курсе",
    topicNamePlaceholder: "Название темы",
    addTestsAndMaterials: "Добавьте тесты и дополнительные материалы",
    tests: "Тесты",
    addTest: "Добавить тест",
    addNewTest: "Добавить новый тест",
    enterTestInfoAndQuestionCount: "Введите информацию о тесте и количество вопросов",
    testName: "Название теста",
    testDescription: "Описание теста",
    testDescriptionPlaceholder: "Описание того, что охватывает этот тест",
    questionCount: "Количество вопросов",
    timeLimit: "Ограничение по времени",
    minutes: "минуты",
    passingScore: "Проходной балл",
    createTest: "Создать тест",
    editTest: "Редактировать тест",
    editTestInfoAndQuestions: "Редактировать информацию о тесте и вопросы",
    questions: "Вопросы",
    addQuestion: "Добавить вопрос",
    noQuestionsYet: "Пока нет вопросов",
    questionText: "Текст вопроса",
    questionTextPlaceholder: "Введите вопрос",
    answerOptions: "Варианты ответов",
    addOption: "Добавить вариант",
    answer: "Ответ",
    correctAnswerExplanation: "Объяснение правильного ответа",
    whyCorrectAnswerExplanation: "Объясните, почему это правильный ответ",
    deleteQuestion: "Удалить вопрос",
    noTestsYet: "Пока нет тестов",
    additionalMaterials: "Дополнительные материалы",
    addMaterial: "Добавить материал",
    materialNamePlaceholder: "Название материала",
    fileType: "Тип файла",
    archive: "Архив",
    link: "Ссылка",
    fileUrlOrLinkPlaceholder: "URL файла или ссылка",
    materialDescriptionPlaceholder: "Описание этого материала",
    noAdditionalMaterialsYet: "Пока нет дополнительных материалов",
    adjustAdditionalSettings: "Настройте дополнительные параметры для курса",
    isCourseVisibleToUsers: "Виден ли этот курс пользователям?",

    // Application details
    applicationDetails: "Детали заявки",
    submittedDate: "Дата подачи",
    positionDetails: "Детали позиции",
    personalInformation: "Личная информация",
    motivationLetter: "Мотивационное письмо",
    documents: "Документы",
    resume: "Резюме",
    passport: "Паспорт",
    diploma: "Диплом",
    certificates: "Сертификаты",
    download: "Скачать",
    statusNew: "Новая",
    statusReviewed: "Рассмотрена",
    statusInterviewed: "Проведено интервью",
    statusAccepted: "Принята",
    statusRejected: "Отклонена",
    statusUnknown: "Неизвестно",
    statusUpdated: "Статус обновлен",
    applicationStatusUpdatedSuccessfully: "Статус заявки успешно обновлен",
    applicationNotFound: "Заявка не найдена",
    failedToLoadApplication: "Не удалось загрузить данные заявки",
    failedToUpdateApplicationStatus: "Не удалось обновить статус заявки",

    // Logout
    logoutSuccess: "Выход выполнен",
    logoutSuccessMessage: "Вы успешно вышли из системы",

    // Teachers
    teacherManagement: "Управление преподавателями",
    addTeacher: "Добавить преподавателя",
    editTeacher: "Редактировать преподавателя",
    deleteTeacher: "Удалить преподавателя",
    teacherName: "Имя преподавателя",
    teacherEmail: "Email",
    teacherPhone: "Телефон",
    teacherSpecialization: "Специализация",
    teacherCourses: "Курсы",
    teachersList: "Список преподавателей",
    manageTeachers: "Управление преподавателями",
    teacherPosition: "Должность",
    teacherSpecialty: "Специальность",
    teacherExperience: "Опыт",
    manageAllTeachers: "Управление всеми преподавателями в системе",
    addNewTeacher: "Добавить нового преподавателя",
    teacherInformation: "Информация о преподавателе",
    fillAllTeacherInfo: "Заполните всю информацию о преподавателе",
    fullName: "Полное имя",
    namePlaceholder: "Введите полное имя",
    email: "Email",
    emailPlaceholder: "Введите адрес электронной почты",
    phone: "Телефон",
    phonePlaceholder: "Введите номер телефона",
    specialization: "Специализация",
    specializationPlaceholder: "Введите специализацию",
    status: "Статус",
    selectStatus: "Выберите статус",
    noCourseAvailable: "Нет доступных курсов",
    saving: "Сохранение...",
    teacherAdded: "Преподаватель добавлен",
    teacherAddedSuccess: "Преподаватель успешно добавлен",
    teacherDeleted: "Преподаватель удален",
    teacherDeletedSuccess: "Преподаватель успешно удален",
    teacherDeletedNotification: "был удален из преподавательского состава",
    confirmDeleteTeacher: "Подтвердите удаление преподавателя",
    deleteTeacherWarning: "Вы уверены, что хотите удалить этого преподавателя? Это действие нельзя отменить.",
    searchTeachers: "Поиск преподавателей...",
    teacherLoadError: "Ошибка загрузки преподавателей",
    teacherLoadErrorMessage: "Произошла ошибка при загрузке преподавателей",
    newTeacher: "Новый преподаватель",
    position: "Должность",
    specialty: "Специальность",
    experience: "Опыт",
    assignedCourses: "Назначенные курсы",
    teacher: "Преподаватель",
    englishLanguage: "Английский язык",
    unknown: "Неизвестно",
    teacherBio: "является опытным преподавателем",
    azizaBio: "Азиза - старший преподаватель английского языка с большим опытом обучения IT-специалистов",
    boburBio:
      "Бобур специализируется на преподавании английского языка для IT-специалистов с акцентом на техническую лексику",
    jasurBio: "Жасур - старший веб-разработчик, который преподает современные веб-технологии",
    dilshodBio: "Дилшод - разработчик Python и инструктор с фокусом на науку о данных",
    malikaBio: "Малика - разработчик Java и инструктор с опытом в корпоративных приложениях",
    seniorEnglishTeacher: "Старший преподаватель английского языка",
    itEnglishSpecialist: "Специалист по IT-английскому",
    seniorWebDeveloper: "Старший веб-разработчик",
    pythonDeveloper: "Python разработчик",
    javaDeveloper: "Java разработчик",
    itEnglish: "IT-английский",
    webDevelopment: "Веб-разработка",
    pythonProgramming: "Программирование на Python",
    javaProgramming: "Программирование на Java",
    years: "лет",
    new: "Новый",
    noPermissionAddTeachers: "У вас нет разрешения на добавление преподавателей",
    coursesLoadError: "Ошибка загрузки курсов",
    activeValue: "active",
    addTeacherError: "Ошибка добавления преподавателя",
    addTeacherErrorMessage: "Произошла ошибка при добавлении преподавателя",

    // Jobs
    jobManagement: "Управление вакансиями",
    addJob: "Добавить вакансию",
    editJob: "Редактировать вакансию",
    deleteJob: "Удалить вакансию",
    jobTitle: "Название вакансии",
    jobCompany: "Компания",
    jobLocation: "Местоположение",
    jobType: "Тип работы",
    jobSalary: "Зарплата",
    jobDescription: "Описание",
    jobRequirements: "Требования",
    jobsList: "Список вакансий",
    manageJobs: "Управление вакансиями",
    jobApplications: "Заявки на вакансии",
    newJobListing: "Новая вакансия",
    jobListings: "Список вакансий",
    applications: "Заявки",
    position: "Должность",
    company: "Компания",
    location: "Местоположение",
    salary: "Зарплата",
    status: "Статус",
    applicationId: "ID заявки",
    applicantName: "Имя заявителя",
    dateSubmitted: "Дата подачи",
    viewApplication: "Просмотреть заявку",
    addNewJobListing: "Добавить новую вакансию",
    jobListingDetails: "Детали вакансии",
    fillFormToCreateNewJob: "Заполните форму для создания новой вакансии",
    positionName: "Название должности",
    positionNamePlaceholder: "например, Старший Frontend-разработчик",
    companyPlaceholder: "например, TechGlobal Inc.",
    locationPlaceholder: "например, Берлин, Германия",
    selectJobType: "Выберите тип работы",
    fullTime: "Полная занятость",
    partTime: "Частичная занятость",
    contract: "Контракт",
    remote: "Удаленная работа",
    salaryPlaceholder: "например, $80,000 - $100,000",
    jobDescriptionPlaceholder: "Подробное описание вакансии...",
    requirement: "Требование",
    addRequirement: "Добавить требование",
    addJobListing: "Добавить вакансию",
    jobAdded: "Вакансия добавлена",
    jobAddedSuccess: "Вакансия успешно добавлена",
    requirementsError: "Пожалуйста, добавьте хотя бы одно требование",
    jobSaveError: "Ошибка сохранения вакансии",
    deleteJobListing: "Удалить вакансию",
    deleteJobConfirmation: "Вы уверены, что хотите удалить эту вакансию?",
    noJobListingsFound: "Вакансии не найдены",
    noJobListingsYet: "Вы еще не создали ни одной вакансии",
    addFirstJobListing: "Добавить первую вакансию",
    searchApplications: "Поиск заявок...",
    searchJobs: "Поиск вакансий...",
    noApplicationsFound: "Заявки не найдены",
    noApplicationsYet: "Заявки еще не поступали",
    new: "Новая",
    reviewed: "Рассмотрена",
    interviewed: "Проведено интервью",
    accepted: "Принята",
    rejected: "Отклонена",

    // Reports
    reports: "Отчеты",
    generateReport: "Создать отчет",
    salesReport: "Отчет о продажах",
    userReport: "Отчет о пользователях",
    courseReport: "Отчет о курсах",
    revenueByPaymentMethod: "Доход по способу оплаты",
    revenueByCourse: "Доход по курсам",
    monthlyRevenue: "Ежемесячный доход",
    downloadReport: "Скачать отчет",
    timeRange: "Временной диапазон",
    lastWeek: "Последняя неделя",
    lastMonth: "Последний месяц",
    lastYear: "Последний год",
    allTime: "За все время",
    downloadingReport: "Скачивание отчета",
    downloading: "скачивается",
    totalRevenuePerCourse: "Общий доход по курсам",
    totalRevenuePerPaymentMethod: "Общий доход по способам оплаты",
    monthlyRevenueForLast12Months: "Ежемесячный доход за последние 12 месяцев",
    userActivityInformation: "Информация об активности пользователей",
    currency: "сум",

    // Settings
    systemSettings: "Системные настройки",
    generalSettings: "Общие настройки",
    notificationSettings: "Настройки уведомлений",
    paymentSettings: "Настройки оплаты",
    securitySettings: "Настройки безопасности",
    changeBasicInformationForSite: "Изменить основную информацию для сайта",
    siteName: "Название сайта",
    siteDescription: "Описание сайта",
    contactEmail: "Контактный email",
    contactPhone: "Контактный телефон",
    address: "Адрес",
    settingsSaved: "Настройки сохранены",
    allSettingsSavedSuccessfully: "Все настройки успешно сохранены",
    chooseNotificationsToReceive: "Выберите, какие уведомления вы хотите получать",
    emailNotifications: "Email уведомления",
    receiveSystemNotificationsViaEmail: "Получать системные уведомления по email",
    newUserNotifications: "Уведомления о новых пользователях",
    receiveNotificationWhenNewUserRegisters: "Получать уведомления при регистрации нового пользователя",
    newOrderNotifications: "Уведомления о новых заказах",
    receiveNotificationWhenNewOrderPlaced: "Получать уведомления при размещении нового заказа",
    marketingEmails: "Маркетинговые письма",
    receiveMarketingAndNewsEmails: "Получать маркетинговые и новостные письма",
    configurePaymentMethods: "Настройка способов оплаты",
    bankTransfer: "Банковский перевод",
    bankDetails: "Банковские реквизиты",
    cash: "Наличные",

    // Website
    websiteSettings: "Настройки веб-сайта",
    homepageSettings: "Настройки главной страницы",
    socialMediaSettings: "Настройки социальных сетей",
    mediaSettings: "Настройки медиа",
    websiteManagement: "Управление веб-сайтом",
    noPermissionWebsite:
      "У вас нет разрешения на управление настройками веб-сайта. Пожалуйста, обратитесь к администратору.",
    general: "Общие",
    homePage: "Главная страница",
    socialMedia: "Социальные сети",
    media: "Медиа",
    configureHomepage: "Настройте внешний вид главной страницы",
    heroTitle: "Заголовок баннера",
    heroDescription: "Описание баннера",
    showFeaturedCourses: "Показывать популярные курсы",
    showFeaturedCoursesDescription: "Показывать раздел популярных курсов на главной странице",
    showTestimonials: "Показывать отзывы",
    showTestimonialsDescription: "Показывать раздел отзывов студентов на главной странице",
    showPartners: "Показывать партнеров",
    showPartnersDescription: "Показывать раздел партнеров на главной странице",
    configureSocialLinks: "Настройте ссылки на социальные сети",
    manageMediaFiles: "Управление медиа-файлами для веб-сайта",
    mediaManagementComingSoon: "Управление медиа-файлами будет добавлено в ближайшее время",
    saving: "Сохранение...",
    lightTheme: "Светлая",
    darkTheme: "Темная",
    systemTheme: "Системная",
    toggleTheme: "Переключить тему",

    // Analytics page
    analytics: "Аналитика",
    downloadReport: "Скачать отчет",
    overview: "Обзор",
    users: "Пользователи",
    courses: "Курсы",
    revenue: "Доход",
    userStatistics: "Статистика пользователей",
    courseStatistics: "Статистика курсов",
    revenueStatistics: "Статистика доходов",
    activityLast30Days: "Активность за последние 30 дней",
    chartDataWillBeDisplayed: "Данные графика будут отображены здесь",
    allTime: "За все время",
    currentMonth: "Текущий месяц",
    average: "В среднем",

    // Schedule page translations
    scheduleManagement: "Управление расписанием",
    weeklySchedule: "Недельное расписание",
    addNewClass: "Добавить новое занятие",
    time: "Время",
    room: "Аудитория",
    noClassesForDay: "На этот день занятия не запланированы",
    editSchedule: "Редактировать расписание",
    addSchedule: "Добавить в расписание",
    day: "День",
    selectDay: "Выберите день",
    monday: "Понедельник",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    sunday: "Воскресенье",
    noClassesScheduled: "Занятия не запланированы",

    // Course management specific translations
    courseBasicInfo: "Основная информация",
    courseContent: "Содержание курса",
    courseTopics: "Темы курса",
    courseTests: "Тесты",
    courseSettings: "Настройки курса",
    addNewCourse: "Добавить новый курс",
    courseName: "Название курса",
    imageUrl: "URL изображения",
    shortDescription: "Краткое описание",
    detailedDescription: "Подробное описание",
    level: "Уровень",
    duration: "Продолжительность",
    numberOfLessons: "Количество уроков",
    priceInSom: "Цена (сум)",
    instructor: "Преподаватель",
    instructorPosition: "Должность преподавателя",
    instructorImageUrl: "URL фото преподавателя",
    addModule: "Добавить модуль",
    addLesson: "Добавить урок",
    testsAndMaterials: "Тесты и материалы",
    moduleTitle: "Модуль",
    lessonTitle: "Урок",
    moduleNamePlaceholder: "Название модуля",
    lessonNamePlaceholder: "Название урока",
    lessonContentPlaceholder: "Содержание урока",
    videoUrlPlaceholder: "URL видео",
    upload: "Загрузить",
    topicNamePlaceholder: "Название темы",
    addTopic: "Добавить тему",
    newTopic: "Новая тема",
    material: "Материал",
    additionalLearningMaterial: "Дополнительный учебный материал",
    materialNamePlaceholder: "Название материала",
    materialDescriptionPlaceholder: "Описание материала",
    test: "Тест",
    testDescription: "Описание теста",
    question: "Вопрос",
    correctAnswerExplanation: "Объяснение правильного ответа",
    newQuestion: "Новый вопрос",
    editCourse: "Редактировать курс",
    editCourseInfo: "Редактировать информацию о курсе",
    loadingCourseData: "Загрузка данных курса...",
    applicationStatusUpdated: "Статус заявки обновлен",
    yourApplicationFor: "Ваша заявка на",
    hasBeenUpdatedTo: "была обновлена до",
    job: "вакансию",

    // Chat page translations
    supportChat: "Чат поддержки",
    chatWithStudents: "Общайтесь со студентами и оказывайте поддержку",
    allChats: "Все чаты",
    unread: "Непрочитанные",
    archived: "Архивированные",
    searchConversations: "Поиск разговоров...",
    noConversationsFound: "Разговоры не найдены",
    online: "В сети",
    selectConversation: "Выберите разговор",
    selectConversationDescription: "Выберите разговор из списка, чтобы начать общение",
    unreadMessages: "Непрочитанные сообщения",
    unreadMessagesDescription: "Сообщения, которые еще не были прочитаны",
    archivedChats: "Архивированные чаты",
    archivedChatsDescription: "Разговоры, которые были архивированы",
    typeMessage: "Введите сообщение...",
    send: "Отправить",
  },
  uz: {
    // Dashboard
    dashboard: "Boshqaruv paneli",
    totalUsers: "Jami foydalanuvchilar",
    totalCourses: "Jami kurslar",
    monthlyIncome: "Oylik daromad",
    activeStudents: "Faol o'quvchilar",
    recentRegistrations: "So'nggi ro'yxatdan o'tganlar",
    recentPurchases: "So'nggi xaridlar",
    comparedToLastMonth: "o'tgan oyga nisbatan",

    // Navigation
    users: "Foydalanuvchilar",
    courses: "Kurslar",
    teachers: "O'qituvchilar",
    jobs: "Ish o'rinlari",
    schedule: "Jadval",
    chat: "Chat",
    analytics: "Tahlillar",
    reports: "Hisobotlar",
    settings: "Sozlamalar",
    website: "Veb-sayt",
    help: "Yordam",
    logout: "Chiqish",
    backToSite: "Saytga qaytish",
    viewSite: "Saytga o'tish",

    // Language
    language: "Til",
    english: "Ingliz",
    russian: "Rus",
    uzbek: "O'zbek",

    // Theme
    darkMode: "Qorong'u rejim",
    lightMode: "Yorug' rejim",
    systemTheme: "Tizim",
    toggleTheme: "Mavzuni o'zgartirish",

    // General
    adminPanel: "Admin panel",
    search: "Qidirish",
    add: "Qo'shish",
    edit: "Tahrirlash",
    delete: "O'chirish",
    save: "Saqlash",
    cancel: "Bekor qilish",
    confirm: "Tasdiqlash",
    back: "Orqaga",
    next: "Keyingi",
    previous: "Oldingi",
    loading: "Yuklanmoqda...",
    noResults: "Natijalar topilmadi",
    error: "Xatolik",
    success: "Muvaffaqiyatli",

    // Application details
    applicationDetails: "Ariza ma'lumotlari",
    submittedDate: "Topshirilgan sana",
    positionDetails: "Lavozim ma'lumotlari",
    personalInformation: "Shaxsiy ma'lumotlar",
    motivationLetter: "Motivatsion xat",
    documents: "Hujjatlar",
    resume: "Rezyume",
    passport: "Passport",
    diploma: "Diplom",
    certificates: "Sertifikatlar",
    download: "Yuklab olish",
    statusNew: "Yangi",
    statusReviewed: "Ko'rib chiqilgan",
    statusInterviewed: "Suhbat o'tkazilgan",
    statusAccepted: "Qabul qilingan",
    statusRejected: "Rad etilgan",
    statusUnknown: "Noma'lum",
    statusUpdated: "Status yangilandi",
    applicationStatusUpdatedSuccessfully: "Ariza statusi muvaffaqiyatli yangilandi",
    applicationNotFound: "Ariza topilmadi",
    failedToLoadApplication: "Ariza ma'lumotlarini yuklashda xatolik yuz berdi",
    failedToUpdateApplicationStatus: "Ariza statusini yangilashda xatolik yuz berdi",

    // Logout
    logoutSuccess: "Tizimdan chiqildi",
    logoutSuccessMessage: "Siz muvaffaqiyatli tizimdan chiqdingiz",

    // Users
    userManagement: "Foydalanuvchilarni boshqarish",
    addUser: "Foydalanuvchi qo'shish",
    editUser: "Foydalanuvchini tahrirlash",
    deleteUser: "Foydalanuvchini o'chirish",
    userName: "Foydalanuvchi nomi",
    userEmail: "Email",
    userPhone: "Telefon",
    userRole: "Rol",
    userStatus: "Holat",
    active: "Faol",
    inactive: "Faol emas",
    activate: "Faollashtirish",
    deactivate: "Faolsizlantirish",
    permissions: "Ruxsatlar",
    noPermission: "Ruxsat yo'q",
    noPermissionAddUsers: "Foydalanuvchilar qo'shish uchun ruxsatingiz yo'q",
    requiredFieldsError: "Iltimos, barcha majburiy maydonlarni to'ldiring",
    userAdded: "Foydalanuvchi qo'shildi",
    userAddedSuccess: "Foydalanuvchi muvaffaqiyatli qo'shildi",
    addUserError: "Foydalanuvchi qo'shishda xatolik",
    addUserErrorMessage: "Foydalanuvchi qo'shishda xatolik yuz berdi",
    searchPlaceholder: "Foydalanuvchilarni qidirish...",
    registeredAt: "Ro'yxatdan o'tgan sana",
    actions: "Amallar",
    allUsers: "Barcha foydalanuvchilar",
    manageAllUsers: "Tizimdagi barcha foydalanuvchilarni boshqarish",

    // Courses
    courseManagement: "Kurslarni boshqarish",
    addCourse: "Kurs qo'shish",
    editCourse: "Kursni tahrirlash",
    deleteCourse: "Kursni o'chirish",
    courseTitle: "Kurs nomi",
    courseDescription: "Kurs tavsifi",
    coursePrice: "Narx",
    courseLevel: "Daraja",
    courseDuration: "Davomiyligi",
    courseStatus: "Holat",
    beginner: "Boshlang'ich",
    intermediate: "O'rta",
    advanced: "Yuqori",
    allLevels: "Barcha darajalar",
    courseDetails: "Kurs tafsilotlari",
    courseInformation: "Kurs ma'lumotlari",
    courseContent: "Kurs tarkibi",
    courseTopics: "Kurs mavzulari",
    courseSettings: "Kurs sozlamalari",
    course: "Kurs",
    instructor: "O'qituvchi",
    lessons: "Darslar",
    students: "O'quvchilar",
    rating: "Reyting",
    createdAt: "Yaratilgan sana",
    updatedAt: "Yangilangan sana",
    view: "Ko'rish",
    moreFilters: "Ko'proq filtrlar",
    noCoursesFound: "Kurslar topilmadi",
    manageCoursesDescription: "Tizimdagi barcha kurslarni boshqarish",
    searchCourses: "Kurslarni qidirish...",
    showing: "Ko'rsatilmoqda",
    courses: "kurslar",
    totalCourses: "Jami kurslar",
    perPage: "sahifada",
    deleteCourseConfirmation: "Rostdan ham bu kursni o'chirmoqchimisiz?",
    courseDeleted: "Kurs o'chirildi",
    courseDeletedSuccessfully: "Kurs muvaffaqiyatli o'chirildi",
    fillAllRequiredFields: "Iltimos, barcha majburiy maydonlarni to'ldiring",
    errorSavingCourse: "Kursni saqlashda xatolik",
    courseAddedSuccessfully: "Kurs muvaffaqiyatli qo'shildi",
    newCourseAdded: "Yangi kurs qo'shildi",
    courseNowAvailable: "kurs endi mavjud",
    enterCourseBasicInfo: "Kurs haqida asosiy ma'lumotlarni kiriting",
    courseNamePlaceholder: "Kurs nomini kiriting",
    shortDescriptionPlaceholder: "Kursning qisqacha tavsifi",
    detailedDescriptionPlaceholder: "O'quvchilar nimani o'rganishi haqida batafsil tavsif",
    selectLevel: "Darajani tanlang",
    weeks: "hafta",
    instructorNamePlaceholder: "O'qituvchi nomi",
    instructorPositionPlaceholder: "O'qituvchi lavozimi yoki unvoni",
    addModulesAndLessons: "Kurs uchun modullar va darslar qo'shing",
    moduleNamePlaceholder: "Modul nomi",
    lessonNamePlaceholder: "Dars nomi",
    lessonContentPlaceholder: "Dars mazmuni yoki tavsifi",
    durationMinutes: "Davomiyligi (daqiqa)",
    videoUrlPlaceholder: "Video URL",
    enterMainTopicsCovered: "Kursda qamrab olingan asosiy mavzularni kiriting",
    topicNamePlaceholder: "Mavzu nomi",
    addTestsAndMaterials: "Testlar va qo'shimcha materiallar qo'shing",
    tests: "Testlar",
    addTest: "Test qo'shish",
    addNewTest: "Yangi test qo'shish",
    enterTestInfoAndQuestionCount: "Test ma'lumotlari va savollar sonini kiriting",
    testName: "Test nomi",
    testDescription: "Test tavsifi",
    testDescriptionPlaceholder: "Bu test nimani qamrab olishi haqida tavsif",
    questionCount: "Savollar soni",
    timeLimit: "Vaqt chegarasi",
    minutes: "daqiqa",
    passingScore: "O'tish bali",
    createTest: "Test yaratish",
    editTest: "Testni tahrirlash",
    editTestInfoAndQuestions: "Test ma'lumotlari va savollarni tahrirlash",
    questions: "Savollar",
    addQuestion: "Savol qo'shish",
    noQuestionsYet: "Hali savollar yo'q",
    questionText: "Savol matni",
    questionTextPlaceholder: "Savolni kiriting",
    answerOptions: "Javob variantlari",
    addOption: "Variant qo'shish",
    answer: "Javob",
    correctAnswerExplanation: "To'g'ri javob tushuntirishi",
    whyCorrectAnswerExplanation: "Nima uchun bu to'g'ri javob ekanligini tushuntiring",
    deleteQuestion: "Savolni o'chirish",
    noTestsYet: "Hali testlar yo'q",
    additionalMaterials: "Qo'shimcha materiallar",
    addMaterial: "Material qo'shish",
    materialNamePlaceholder: "Material nomi",
    fileType: "Fayl turi",
    archive: "Arxiv",
    link: "Havola",
    fileUrlOrLinkPlaceholder: "Fayl URL yoki havola",
    materialDescriptionPlaceholder: "Bu material tavsifi",
    noAdditionalMaterialsYet: "Hali qo'shimcha materiallar yo'q",
    adjustAdditionalSettings: "Kurs uchun qo'shimcha sozlamalarni o'zgartiring",
    isCourseVisibleToUsers: "Bu kurs foydalanuvchilarga ko'rinadimi?",

    // Teachers
    teacherManagement: "O'qituvchilarni boshqarish",
    addTeacher: "O'qituvchi qo'shish",
    editTeacher: "O'qituvchini tahrirlash",
    deleteTeacher: "O'qituvchini o'chirish",
    teacherName: "O'qituvchi nomi",
    teacherEmail: "Email",
    teacherPhone: "Telefon",
    teacherSpecialization: "Mutaxassislik",
    teacherCourses: "Kurslar",
    teachersList: "O'qituvchilar ro'yxati",
    manageTeachers: "O'qituvchilarni boshqarish",
    teacherPosition: "Lavozim",
    teacherSpecialty: "Mutaxassislik",
    teacherExperience: "Tajriba",
    manageAllTeachers: "Barcha o'qituvchilarni boshqarish",
    addNewTeacher: "Yangi o'qituvchi qo'shish",
    teacherInformation: "O'qituvchi ma'lumotlari",
    fillAllTeacherInfo: "O'qituvchi haqidagi barcha ma'lumotlarni to'ldiring",
    fullName: "To'liq ism",
    namePlaceholder: "To'liq ismni kiriting",
    email: "Email",
    emailPlaceholder: "Email manzilini kiriting",
    phone: "Telefon",
    phonePlaceholder: "Telefon raqamini kiriting",
    specialization: "Mutaxassislik",
    specializationPlaceholder: "Mutaxassislikni kiriting",
    status: "Holat",
    selectStatus: "Holatni tanlang",
    noCourseAvailable: "Mavjud kurslar yo'q",
    saving: "Saqlanmoqda...",
    teacherAdded: "O'qituvchi qo'shildi",
    teacherAddedSuccess: "O'qituvchi muvaffaqiyatli qo'shildi",
    teacherDeleted: "O'qituvchi o'chirildi",
    teacherDeletedSuccess: "O'qituvchi muvaffaqiyatli o'chirildi",
    teacherDeletedNotification: "o'qituvchilar tarkibidan olib tashlandi",
    confirmDeleteTeacher: "O'qituvchini o'chirishni tasdiqlang",
    deleteTeacherWarning: "Rostdan ham bu o'qituvchini o'chirmoqchimisiz? Bu amalni qaytarib bo'lmaydi.",
    searchTeachers: "O'qituvchilarni qidirish...",
    teacherLoadError: "O'qituvchilarni yuklashda xatolik",
    teacherLoadErrorMessage: "O'qituvchilarni yuklashda xatolik yuz berdi",
    newTeacher: "Yangi o'qituvchi",
    position: "Lavozim",
    specialty: "Mutaxassislik",
    experience: "Tajriba",
    assignedCourses: "Biriktirilgan kurslar",
    teacher: "O'qituvchi",
    englishLanguage: "Ingliz tili",
    unknown: "Noma'lum",
    teacherBio: "tajribali o'qituvchi hisoblanadi",
    azizaBio:
      "Aziza IT mutaxassislariga ingliz tilini o'rgatishda katta tajribaga ega yuqori darajali ingliz tili o'qituvchisi",
    boburBio:
      "Bobur texnik lug'atga e'tibor qaratgan holda IT mutaxassislariga ingliz tilini o'rgatishga ixtisoslashgan",
    jasurBio: "Jasur zamonaviy veb-texnologiyalarni o'rgatadigan yuqori darajali veb-dasturchi",
    dilshodBio: "Dilshod ma'lumotlar fani yo'nalishida Python dasturchi va o'qituvchi",
    malikaBio: "Malika korporativ ilovalar bo'yicha tajribaga ega Java dasturchi va o'qituvchi",
    seniorEnglishTeacher: "Yuqori darajali ingliz tili o'qituvchisi",
    itEnglishSpecialist: "IT ingliz tili mutaxassisi",
    seniorWebDeveloper: "Yuqori darajali veb-dasturchi",
    pythonDeveloper: "Python dasturchi",
    javaDeveloper: "Java dasturchi",
    itEnglish: "IT ingliz tili",
    webDevelopment: "Veb-dasturlash",
    pythonProgramming: "Python dasturlash",
    javaProgramming: "Java dasturlash",
    years: "yil",
    new: "Yangi",
    noPermissionAddTeachers: "O'qituvchilar qo'shish uchun ruxsatingiz yo'q",
    coursesLoadError: "Kurslarni yuklashda xatolik",
    activeValue: "active",
    addTeacherError: "O'qituvchi qo'shishda xatolik",
    addTeacherErrorMessage: "O'qituvchi qo'shishda xatolik yuz berdi",

    // Jobs
    jobManagement: "Ish boshqaruvi",
    addJob: "Ish qo'shish",
    editJob: "Ishni tahrirlash",
    deleteJob: "Ishni o'chirish",
    jobTitle: "Lavozim nomi",
    jobCompany: "Kompaniya",
    jobLocation: "Joylashuv",
    jobType: "Ish turi",
    jobSalary: "Maosh",
    jobDescription: "Tavsif",
    jobRequirements: "Talablar",
    jobsList: "Ishlar ro'yxati",
    manageJobs: "Ishlarni boshqarish",
    jobApplications: "Ish arizalari",
    newJobListing: "Yangi ish e'loni",
    jobListings: "Ish e'lonlari",
    applications: "Arizalar",
    position: "Lavozim",
    company: "Kompaniya",
    location: "Joylashuv",
    salary: "Maosh",
    status: "Holat",
    applicationId: "Ariza ID",
    applicantName: "Ariza beruvchi ismi",
    dateSubmitted: "Topshirilgan sana",
    viewApplication: "Arizani ko'rish",
    addNewJobListing: "Yangi ish e'loni qo'shish",
    jobListingDetails: "Ish e'loni tafsilotlari",
    fillFormToCreateNewJob: "Yangi ish e'loni yaratish uchun formani to'ldiring",
    positionName: "Lavozim nomi",
    positionNamePlaceholder: "masalan, Yuqori darajali Frontend dasturchi",
    companyPlaceholder: "masalan, TechGlobal Inc.",
    locationPlaceholder: "masalan, Berlin, Germaniya",
    selectJobType: "Ish turini tanlang",
    fullTime: "To'liq stavka",
    partTime: "Yarim stavka",
    contract: "Shartnoma asosida",
    remote: "Masofaviy",
    salaryPlaceholder: "masalan, $80,000 - $100,000",
    jobDescriptionPlaceholder: "Batafsil ish tavsifi...",
    requirement: "Talab",
    addRequirement: "Talab qo'shish",
    addJobListing: "Ish e'lonini qo'shish",
    jobAdded: "Ish e'loni qo'shildi",
    jobAddedSuccess: "Ish e'loni muvaffaqiyatli qo'shildi",
    requirementsError: "Iltimos, kamida bitta talab qo'shing",
    jobSaveError: "Ish e'lonini saqlashda xatolik",
    deleteJobListing: "Ish e'lonini o'chirish",
    deleteJobConfirmation: "Rostdan ham bu ish e'lonini o'chirmoqchimisiz?",
    noJobListingsFound: "Ish e'lonlari topilmadi",
    noJobListingsYet: "Siz hali hech qanday ish e'loni yaratmagansiz",
    addFirstJobListing: "Birinchi ish e'lonini qo'shish",
    searchApplications: "Arizalarni qidirish...",
    searchJobs: "Ish e'lonlarini qidirish...",
    noApplicationsFound: "Arizalar topilmadi",
    noApplicationsYet: "Hali arizalar topshirilmagan",
    new: "Yangi",
    reviewed: "Ko'rib chiqilgan",
    interviewed: "Suhbat o'tkazilgan",
    accepted: "Qabul qilingan",
    rejected: "Rad etilgan",

    // Reports
    reports: "Hisobotlar",
    generateReport: "Hisobot yaratish",
    salesReport: "Sotuvlar hisoboti",
    userReport: "Foydalanuvchilar hisoboti",
    courseReport: "Kurslar hisoboti",
    revenueByPaymentMethod: "To'lov usuli bo'yicha daromad",
    revenueByCourse: "Kurs bo'yicha daromad",
    monthlyRevenue: "Oylik daromad",
    downloadReport: "Hisobotni yuklab olish",
    timeRange: "Vaqt oralig'i",
    lastWeek: "So'nggi hafta",
    lastMonth: "So'nggi oy",
    lastYear: "So'nggi yil",
    allTime: "Barcha vaqt",
    downloadingReport: "Hisobot yuklab olinmoqda",
    downloading: "yuklab olinmoqda",
    totalRevenuePerCourse: "Har bir kurs bo'yicha jami daromad",
    totalRevenuePerPaymentMethod: "Har bir to'lov usuli bo'yicha jami daromad",
    monthlyRevenueForLast12Months: "So'nggi 12 oy uchun oylik daromad",
    userActivityInformation: "Foydalanuvchilar va ularning faolligi haqida ma'lumot",
    currency: "so'm",

    // Settings
    systemSettings: "Tizim sozlamalari",
    generalSettings: "Umumiy sozlamalar",
    notificationSettings: "Bildirishnoma sozlamalari",
    paymentSettings: "To'lov sozlamalari",
    securitySettings: "Xavfsizlik sozlamalari",
    changeBasicInformationForSite: "Sayt uchun asosiy ma'lumotlarni o'zgartiring",
    siteName: "Sayt nomi",
    siteDescription: "Sayt tavsifi",
    contactEmail: "Aloqa email",
    contactPhone: "Aloqa telefoni",
    address: "Manzil",
    settingsSaved: "Sozlamalar saqlandi",
    allSettingsSavedSuccessfully: "Barcha sozlamalar muvaffaqiyatli saqlandi",
    chooseNotificationsToReceive: "Qaysi bildirishnomalarni olishni xohlaysiz",
    emailNotifications: "Email bildirishnomalari",
    receiveSystemNotificationsViaEmail: "Tizim bildirishnomalarini email orqali olish",
    newUserNotifications: "Yangi foydalanuvchilar",
    receiveNotificationWhenNewUserRegisters: "Yangi foydalanuvchi ro'yxatdan o'tganda bildirishnoma olish",
    newOrderNotifications: "Yangi buyurtmalar",
    receiveNotificationWhenNewOrderPlaced: "Yangi buyurtma qilinganda bildirishnoma olish",
    marketingEmails: "Marketing xabarlari",
    receiveMarketingAndNewsEmails: "Marketing va yangiliklar haqida xabarlar olish",
    configurePaymentMethods: "To'lov usullarini sozlash",
    bankTransfer: "Bank o'tkazmasi",
    bankDetails: "Bank ma'lumotlari",
    cash: "Naqd pul",

    // Website
    websiteSettings: "Veb-sayt sozlamalari",
    homepageSettings: "Bosh sahifa sozlamalari",
    socialMediaSettings: "Ijtimoiy tarmoq sozlamalari",
    mediaSettings: "Media sozlamalari",
    websiteManagement: "Veb-sayt boshqaruvi",
    noPermissionWebsite:
      "Sizda veb-sayt sozlamalarini boshqarish uchun ruxsat yo'q. Iltimos, administrator bilan bog'laning.",
    general: "Umumiy",
    homePage: "Bosh sahifa",
    socialMedia: "Ijtimoiy tarmoqlar",
    media: "Media",
    configureHomepage: "Bosh sahifa ko'rinishini sozlang",
    heroTitle: "Asosiy sarlavha",
    heroDescription: "Asosiy tavsif",
    showFeaturedCourses: "Mashhur kurslarni ko'rsatish",
    showFeaturedCoursesDescription: "Bosh sahifada mashhur kurslar bo'limini ko'rsatish",
    showTestimonials: "Fikrlarni ko'rsatish",
    showTestimonialsDescription: "Bosh sahifada o'quvchilar fikrlari bo'limini ko'rsatish",
    showPartners: "Hamkorlarni ko'rsatish",
    showPartnersDescription: "Bosh sahifada hamkorlar bo'limini ko'rsatish",
    configureSocialLinks: "Ijtimoiy tarmoq havolalarini sozlang",
    manageMediaFiles: "Sayt uchun media fayllarni boshqaring",
    mediaManagementComingSoon: "Media fayllar boshqaruvi tez orada qo'shiladi",
    saving: "Saqlanmoqda...",
    lightTheme: "Yorug'",
    darkTheme: "Qorong'i",

    // Help page translations
    helpAndSupport: "Yordam va qo'llab-quvvatlash",
    searchHelpPlaceholder: "Savol yoki kalit so'z kiriting...",
    faqDescription: "Tizim haqida eng ko'p so'raladigan savollar va javoblar",
    howToAddCourse: "Yangi kurs qanday qo'shiladi?",
    howToAddCourseAnswer:
      "Yangi kurs qo'shish uchun 'Kurslar' bo'limiga o'ting va 'Yangi kurs qo'shish' tugmasini bosing. Kerakli ma'lumotlarni kiriting va 'Saqlash' tugmasini bosing. Kurs qo'shilgandan so'ng, uni tahrirlash yoki o'chirish mumkin.",
    howToChangeUserPermissions: "Foydalanuvchi huquqlarini qanday o'zgartirish mumkin?",
    howToChangeUserPermissionsAnswer:
      "Foydalanuvchi huquqlarini o'zgartirish uchun 'Foydalanuvchilar' bo'limiga o'ting va kerakli foydalanuvchini tanlang. 'Tahrirlash' tugmasini bosing va foydalanuvchi huquqlarini o'zgartiring. O'zgarishlarni saqlash uchun 'Saqlash' tugmasini bosing.",
    howToDownloadReports: "Hisobotlarni qanday yuklab olish mumkin?",
    howToDownloadReportsAnswer:
      "Hisobotlarni yuklab olish uchun 'Analitika' bo'limiga o'ting va kerakli hisobot turini tanlang. 'Hisobotni yuklab olish' tugmasini bosing va hisobot yuklab olinadi. Hisobotlar Excel, PDF va CSV formatlarida mavjud.",
    whatToDoWhenError: "Tizimda xatolik yuz berganda nima qilish kerak?",
    whatToDoWhenErrorAnswer:
      "Tizimda xatolik yuz berganda, avvalo brauzeringizni yangilang. Agar muammo hal bo'lmasa, tizimdan chiqib, qayta kiring. Agar muammo davom etsa, 'Bog'lanish' bo'limiga o'ting va muammo haqida ma'lumot bering. Texnik qo'llab-quvvatlash xizmati sizga yordam beradi.",
    howToChangeLanguage: "Tizim tilini qanday o'zgartirish mumkin?",
    howToChangeLanguageAnswer:
      "Tizim tilini o'zgartirish uchun yuqori o'ng burchakdagi til tanlov tugmasini bosing va kerakli tilni tanlang. Tizim uch tilda mavjud: o'zbek, rus va ingliz.",

    // Guides section
    guides: "Qo'llanmalar",
    guidesDescription: "Tizimdan foydalanish bo'yicha qo'llanmalar",
    courseManagementGuide: "Kurslarni boshqarish",
    courseManagementGuideDescription: "Kurslarni qo'shish, tahrirlash va o'chirish bo'yicha qo'llanma",
    userManagementGuide: "Foydalanuvchilarni boshqarish",
    userManagementGuideDescription: "Foydalanuvchilarni boshqarish va huquqlarni o'zgartirish bo'yicha qo'llanma",
    reportsGuide: "Hisobotlar bilan ishlash",
    reportsGuideDescription: "Hisobotlarni ko'rish va yuklab olish bo'yicha qo'llanma",
    paymentsGuide: "To'lovlarni boshqarish",
    paymentsGuideDescription: "To'lovlarni kuzatish va boshqarish bo'yicha qo'llanma",
    messagesGuide: "Xabarlarni boshqarish",
    messagesGuideDescription: "Xabarlarni yuborish va qabul qilish bo'yicha qo'llanma",
    systemSettingsGuide: "Tizim sozlamalari",
    systemSettingsGuideDescription: "Tizim sozlamalarini o'zgartirish bo'yicha qo'llanma",
    viewGuide: "Qo'llanmani ko'rish",

    // Contact support section
    contactSupport: "Bog'lanish",
    contactSupportDescription: "Texnik qo'llab-quvvatlash xizmati bilan bog'lanish",
    byEmail: "Email orqali",
    responseTime24Hours: "24 soat ichida javob beramiz",
    byPhone: "Telefon orqali",
    workingHours: "Ish vaqti: 9:00 - 18:00",
    byChat: "Chat orqali",
    byChatDescription: "Online chat orqali bog'laning",
    forQuickResponse: "Tezkor javob olish uchun",
    yourName: "Ismingiz",
    email: "Email",
    subject: "Mavzu",
    message: "Xabar",
    sendMessage: "Xabarni yuborish",
    messageSent: "Xabar yuborildi",
    messageSuccessfullySent: "Sizning xabaringiz muvaffaqiyatli yuborildi. Tez orada javob beramiz.",
    applicationStatusUpdated: "Ariza holati yangilandi",
    yourApplicationFor: "Sizning",
    hasBeenUpdatedTo: "uchun arizangiz holati yangilandi:",
    job: "ish",

    // Help
    helpAndSupport: "Yordam va qo'llab-quvvatlash",
    faq: "Ko'p so'raladigan savollar",
    contactSupport: "Yordam xizmatiga murojaat",
    documentation: "Hujjatlar",

    // Confirmation
    confirmDelete: "Rostdan ham buni o'chirmoqchimisiz?",
    confirmDeleteDescription: "Bu amalni qaytarib bo'lmaydi.",

    // Table
    id: "ID",
    name: "Ism",
    email: "Email",
    phone: "Telefon",
    role: "Rol",
    status: "Holat",
    actions: "Amallar",

    // Pagination
    showing: "Ko'rsatilmoqda",
    of: "dan",
    items: "elementlar",
    perPage: "sahifada",

    // Filters
    filter: "Filtr",
    allStatuses: "Barcha holatlar",
    planned: "Rejada",
    archived: "Arxivlangan",

    // Time
    yesterday: "Kecha",
    today: "Bugun",

    // Errors
    failedToLoadData: "Ma'lumotlarni yuklashda xatolik yuz berdi",
    failedToSaveData: "Ma'lumotlarni saqlashda xatolik yuz berdi",
    accessDenied: "Ruxsat yo'q",

    // Success messages
    savedSuccessfully: "Muvaffaqiyatli saqlandi",
    deletedSuccessfully: "Muvaffaqiyatli o'chirildi",

    // Placeholders
    searchPlaceholder: "Qidirish...",
    emailPlaceholder: "Elektron pochta manzili",
    passwordPlaceholder: "Parol",

    // Buttons
    signIn: "Kirish",
    signOut: "Chiqish",

    // Analytics page
    analytics: "Analitika",
    downloadReport: "Hisobotni yuklab olish",
    overview: "Umumiy",
    users: "Foydalanuvchilar",
    courses: "Kurslar",
    revenue: "Daromad",
    userStatistics: "Foydalanuvchilar statistikasi",
    courseStatistics: "Kurslar statistikasi",
    revenueStatistics: "Daromad statistikasi",
    activityLast30Days: "So'nggi 30 kun ichidagi faollik",
    chartDataWillBeDisplayed: "Grafik ma'lumotlari bu yerda ko'rsatiladi",
    allTime: "Barcha vaqt uchun",
    currentMonth: "Joriy oy",
    average: "O'rtacha",

    // Schedule page translations
    scheduleManagement: "Jadval boshqaruvi",
    weeklySchedule: "Haftalik jadval",
    addNewClass: "Yangi dars qo'shish",
    time: "Vaqt",
    room: "Xona",
    noClassesForDay: "Bu kun uchun darslar rejalashtirilmagan",
    editSchedule: "Jadvalni tahrirlash",
    addSchedule: "Jadvalga qo'shish",
    day: "Kun",
    selectDay: "Kunni tanlang",
    monday: "Dushanba",
    tuesday: "Seshanba",
    wednesday: "Chorshanba",
    thursday: "Payshanba",
    friday: "Juma",
    saturday: "Shanba",
    sunday: "Yakshanba",
    noClassesScheduled: "Darslar rejalashtirilmagan",

    // Course management specific translations
    courseBasicInfo: "Asosiy ma'lumot",
    courseContent: "Kurs mazmuni",
    courseTopics: "Kurs mavzulari",
    courseTests: "Testlar",
    courseSettings: "Kurs sozlamalari",
    addNewCourse: "Yangi kurs qo'shish",
    courseName: "Kurs nomi",
    imageUrl: "Rasm URL",
    shortDescription: "Qisqa tavsif",
    detailedDescription: "Batafsil tavsif",
    level: "Daraja",
    duration: "Davomiyligi",
    numberOfLessons: "Darslar soni",
    priceInSom: "Narxi (so'm)",
    instructor: "O'qituvchi",
    instructorPosition: "O'qituvchi lavozimi",
    instructorImageUrl: "O'qituvchi rasmi URL",
    addModule: "Modul qo'shish",
    addLesson: "Dars qo'shish",
    testsAndMaterials: "Testlar va materiallar",
    moduleTitle: "Modul",
    lessonTitle: "Dars",
    moduleNamePlaceholder: "Modul nomi",
    lessonNamePlaceholder: "Dars nomi",
    lessonContentPlaceholder: "Dars mazmuni",
    videoUrlPlaceholder: "Video URL",
    upload: "Yuklash",
    topicNamePlaceholder: "Mavzu nomi",
    addTopic: "Mavzu qo'shish",
    newTopic: "Yangi mavzu",
    material: "Material",
    additionalLearningMaterial: "Qo'shimcha o'quv materiali",
    materialNamePlaceholder: "Material nomi",
    materialDescriptionPlaceholder: "Material tavsifi",
    test: "Test",
    testDescription: "Test tavsifi",
    question: "Savol",
    correctAnswerExplanation: "To'g'ri javob tushuntirishi",
    newQuestion: "Yangi savol",
    editCourse: "Kursni tahrirlash",
    editCourseInfo: "Kurs ma'lumotlarini tahrirlash",
    loadingCourseData: "Kurs ma'lumotlari yuklanmoqda...",

    // Chat page translations
    supportChat: "Qo'llab-quvvatlash chati",
    chatWithStudents: "Talabalar bilan suhbatlashing va yordam ko'rsating",
    allChats: "Barcha chatlar",
    unread: "O'qilmagan",
    archived: "Arxivlangan",
    searchConversations: "Suhbatlarni qidirish...",
    noConversationsFound: "Suhbatlar topilmadi",
    online: "Onlayn",
    selectConversation: "Suhbatni tanlang",
    selectConversationDescription: "Suhbatlashishni boshlash uchun ro'yxatdan suhbatni tanlang",
    unreadMessages: "O'qilmagan xabarlar",
    unreadMessagesDescription: "Hali o'qilmagan xabarlar",
    archivedChats: "Arxivlangan chatlar",
    archivedChatsDescription: "Arxivlangan suhbatlar",
    typeMessage: "Xabar yozing...",
    send: "Yuborish",
  },
}

// Create context with default values
const AdminLanguageContext = createContext<AdminLanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
  isReady: false,
})

// Storage key for admin language preference
const STORAGE_KEY = "admin-language-preference"

// Provider component
export function AdminLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)
  const [isReady, setIsReady] = useState(false)

  // Load language preference from localStorage on mount
  useEffect(() => {
    // Set mounted to true to avoid hydration mismatch
    setMounted(true)

    if (typeof window !== "undefined") {
      const savedLanguage = localStorage.getItem(STORAGE_KEY) as Language
      if (savedLanguage && ["en", "ru", "uz"].includes(savedLanguage)) {
        setLanguage(savedLanguage)
      } else {
        // Try to detect browser language
        const browserLang = navigator.language.split("-")[0]
        if (browserLang === "ru") {
          setLanguage("ru")
        } else if (browserLang === "uz") {
          setLanguage("uz")
        }
        // Default is already "en"
      }

      // Set HTML lang attribute
      document.documentElement.lang = savedLanguage || "en"

      // Mark as ready after language is loaded
      setIsReady(true)
    }
  }, [])

  // Save language preference to localStorage when it changes
  const handleSetLanguage = (newLang: Language) => {
    setLanguage(newLang)
    if (typeof window !== "undefined") {
      localStorage.setItem(STORAGE_KEY, newLang)

      // Update HTML lang attribute for accessibility
      document.documentElement.lang = newLang

      // Set data attribute for easier styling based on language
      document.documentElement.setAttribute("data-language", newLang)

      // Dispatch a custom event that components can listen for
      const event = new CustomEvent("languageChanged", { detail: { language: newLang } })
      window.dispatchEvent(event)

      // Force refresh of components that might not be listening for the event
      setTimeout(() => {
        const refreshEvent = new Event("resize")
        window.dispatchEvent(refreshEvent)
      }, 100)
    }
  }

  // Translation function with parameter support
  const t = (key: string, params?: Record<string, string | number>): string => {
    // Get the translation for the current language
    let translation = defaultTranslations[language]?.[key] || defaultTranslations.en[key] || key

    // Replace parameters if provided
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, String(paramValue))
      })
    }

    return translation
  }

  // Don't render anything during SSR to avoid hydration issues
  if (!mounted) {
    return <>{children}</>
  }

  const contextValue = {
    language,
    setLanguage: handleSetLanguage,
    t,
    isReady,
  }

  return <AdminLanguageContext.Provider value={contextValue}>{children}</AdminLanguageContext.Provider>
}

// Custom hook to use the admin language context
export function useAdminLanguage() {
  const context = useContext(AdminLanguageContext)
  if (!context) {
    throw new Error("useAdminLanguage must be used within an AdminLanguageProvider")
  }
  return context
}

export default AdminLanguageProvider

