"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect, useCallback } from "react"
import { useRouter, usePathname } from "next/navigation"

// Define available languages
export type Language = "uz" | "ru" | "en"

// Define translations interface
interface Translations {
  [key: string]: {
    [key: string]: string
  }
}

// Define language context type
export interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string>) => string
  translations: Translations
}

// Default translations
const defaultTranslations: Translations = {
  uz: {
    // Add these new translations
    accountInactive: "Hisobingiz faol emas",
    accountInactiveDescription: "Sizning hisobingiz administrator tomonidan o'chirilgan yoki to'xtatilgan",
    loginFailed: "Kirish muvaffaqiyatsiz",
    invalidEmailFormat: "Elektron pochta formati noto'g'ri",
    invalidPhoneFormat: "Telefon raqami formati noto'g'ri",
    usernameAlreadyExists: "Bunday foydalanuvchi nomi allaqachon mavjud",
    // Navigation
    home: "Bosh sahifa",
    courses: "Kurslar",
    jobs: "Ish o'rinlari",
    about: "Biz haqimizda",
    contact: "Bog'lanish",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    profile: "Profil",
    logout: "Chiqish",
    my_courses: "Mening kurslarim",
    cart: "Savatcha",
    search: "Qidirish",
    notifications: "Bildirishnomalar",
    mark_all_as_read: "Barchasini o'qilgan deb belgilash",
    no_notifications: "Bildirishnomalar yo'q",
    language: "Til",
    theme: "Mavzu",
    light: "Yorug'",
    dark: "Qorong'i",
    system: "Tizim",
    adminPanel: "Admin panel",

    // Profile
    welcome_back: "Qaytib kelganingiz bilan",
    welcome_message: "Qaytib kelganingiz bilan, {name}",
    profile_completion: "Profil to'ldirilishi",
    student: "Talaba",
    english_b2: "Ingliz tili B2",
    it_beginner: "IT boshlang'ich",
    edit_profile: "Profilni tahrirlash",
    quick_links: "Tezkor havolalar",
    certificates: "Sertifikatlar",
    support_chat: "Yordam chati",
    browse_courses: "Kurslarni ko'rish",
    overview: "Umumiy ma'lumot",
    progress: "Progress",
    achievements: "Yutuqlar",
    active_courses: "Faol kurslar",
    completed_courses: "Tugatilgan kurslar",
    next_lesson: "Keyingi dars",
    join_now: "Hozir qo'shiling",
    recent_activity: "So'nggi faoliyat",
    view_all_activity: "Barcha faoliyatni ko'rish",
    learning_progress: "O'rganish progressi",
    progress_description: "Barcha kurslardagi progressingizni kuzating",
    your_achievements: "Sizning yutuqlaringiz",
    achievements_description: "Siz erishgan yutuqlar",
    first_course: "Birinchi kurs",
    completed_first_course: "Birinchi kursingizni tugatdingiz",
    coding_streak: "Kod yozish seriyasi",
    seven_day_streak: "7 kunlik o'rganish seriyasini saqlab qoldingiz",
    quiz_master: "Viktorina ustasi",
    perfect_score: "Viktorinada mukammal ball to'pladingiz",
    fast_learner: "Tez o'rganuvchi",
    completed_course_quickly: "Kursni rekord vaqtda tugatdingiz",
    completed_lesson: "Dars tugatildi",
    days_ago: "kun oldin",

    // Settings page
    settings: "Sozlamalar",
    "manage account settings": "Hisob sozlamalarini boshqarish",
    "profile information": "Profil ma'lumotlari",
    "update profile information": "Profil ma'lumotlarini yangilash",
    "change avatar": "Avatarni o'zgartirish",
    "remove avatar": "Avatarni olib tashlash",
    "first name": "Ism",
    "last name": "Familiya",
    bio: "Biografiya",
    "tell us about yourself": "O'zingiz haqingizda gapirib bering",
    "preferred language": "Afzal ko'rilgan til",
    "select language": "Tilni tanlang",
    cancel: "Bekor qilish",
    "save changes": "O'zgarishlarni saqlash",
    "account settings": "Hisob sozlamalari",
    "update account settings": "Hisob sozlamalarini yangilash",
    email: "Elektron pochta",
    "change password": "Parolni o'zgartirish",
    "current password": "Joriy parol",
    "new password": "Yangi parol",
    "confirm password": "Parolni tasdiqlang",
    "danger zone": "Xavfli zona",
    "danger zone description": "Bu harakatlar qaytarib bo'lmaydigan va hisobingizni butunlay o'chirib tashlaydi",
    "delete account": "Hisobni o'chirish",
    "notification settings": "Bildirishnoma sozlamalari",
    "manage notification preferences": "Bildirishnoma afzalliklarini boshqarish",
    "email notifications": "Elektron pochta bildirishnomalari",
    "receive email notifications": "Elektron pochta orqali bildirishnomalarni qabul qilish",
    "push notifications": "Push bildirishnomalari",
    "receive push notifications": "Push bildirishnomalarini qabul qilish",
    "marketing emails": "Marketing xabarlari",
    "receive marketing emails": "Marketing xabarlarini qabul qilish",
    "course updates": "Kurs yangilanishlari",
    "receive course updates": "Kurs yangilanishlarini qabul qilish",
    "lesson reminders": "Dars eslatmalari",
    "receive lesson reminders": "Dars eslatmalarini qabul qilish",
    loading: "Yuklanmoqda...",

    // Homepage
    learnEnglishForIT: "IT sohasida ingliz tilini o'rganing",
    academyDescription: "IT English Academy - IT mutaxassislari uchun maxsus ingliz tili kurslari",
    viewCourses: "Kurslarni ko'rish",
    contactUs: "Biz bilan bog'lanish",
    academyImageAlt: "IT English Academy talabalar",
    ourAdvantages: "Bizning afzalliklarimiz",
    whyChooseUs: "Nima uchun bizni tanlaysiz",
    itEnglish: "IT ingliz tili",
    itEnglishDescription: "IT sohasiga maxsus mo'ljallangan ingliz tili kurslari",
    modernTeaching: "Zamonaviy o'qitish",
    modernTeachingDescription: "Eng so'nggi o'qitish metodlari va texnologiyalaridan foydalanish",
    experiencedTeachers: "Tajribali o'qituvchilar",
    experiencedTeachersDescription: "IT va ingliz tili sohasida tajribali o'qituvchilar",
    practicalExercises: "Amaliy mashg'ulotlar",
    practicalExercisesDescription: "Haqiqiy IT loyihalarda qo'llaniladigan amaliy mashg'ulotlar",
    smallGroups: "Kichik guruhlar",
    smallGroupsDescription: "Har bir talabaga individual yondashish uchun kichik guruhlar",
    guaranteedResult: "Kafolatlangan natija",
    guaranteedResultDescription: "Kursni tugatgandan so'ng kafolatlangan natija",
    popularCourses: "Mashhur kurslar",
    explorePopularCourses: "Eng mashhur kurslarimizni ko'rib chiqing",
    englishBasics: "Ingliz tili asoslari",
    englishBasicsDescription: "IT sohasida ishlash uchun zarur bo'lgan ingliz tili asoslari",
    webDevelopment: "Veb-dasturlash",
    webDevelopmentDescription: "Veb-dasturlash asoslari va ingliz tilida texnik hujjatlarni o'qish",
    price1: "800,000 so'm",
    price2: "1,200,000 so'm",
    price3: "1,500,000 so'm",
    details: "Batafsil",
    registerNow: "Hozir ro'yxatdan o'ting",
    registerNowDescription: "Kurslarimizga ro'yxatdan o'ting va IT sohasida ingliz tilini o'rganishni boshlang",
    register: "Ro'yxatdan o'tish",
    pages: "Sahifalar",
    address: "Toshkent sh., Yunusobod tumani, 4-mavze",
    phone: "+998 90 123 45 67",
    email: "info@itenglish.academy",
    socialMedia: "Ijtimoiy tarmoqlar",
    allRightsReserved: "Barcha huquqlar himoyalangan",

    // About page
    backToHome: "Bosh sahifaga qaytish",
    aboutHeroText: "IT English Academy - IT mutaxassislari uchun maxsus ingliz tili kurslari",
    ourMission: "Bizning vazifamiz",
    missionText1:
      "IT English Academy - bu IT sohasida ishlash uchun zarur bo'lgan ingliz tilini o'rgatishga ixtisoslashgan o'quv markazi.",
    missionText2:
      "Bizning maqsadimiz - IT mutaxassislariga ingliz tilini o'rgatish orqali ularning xalqaro miqyosda raqobatbardoshligini oshirish.",
    students: "Talabalar",
    qualifiedTeachers: "Malakali o'qituvchilar",
    yearsExperience: "Yillik tajriba",
    ourTeam: "Bizning jamoa",
    teamDescription: "IT English Academy jamoasi - bu IT va ingliz tili sohasida tajribali mutaxassislar",
    headTeacher: "Bosh o'qituvchi",
    itDepartmentHead: "IT bo'limi boshlig'i",
    academicDepartmentHead: "O'quv bo'limi boshlig'i",
    azizaBio: "10 yillik ingliz tili o'qitish tajribasiga ega. IT sohasida ingliz tilini o'qitish bo'yicha mutaxassis.",
    boburBio: "5 yillik IT sohasida ishlash tajribasiga ega. Full-stack dasturchi va o'qituvchi.",
    malikaBio: "8 yillik o'quv dasturlarini ishlab chiqish tajribasiga ega. Ta'lim metodisti.",
    ourValues: "Bizning qadriyatlarimiz",
    valuesDescription:
      "IT English Academy qadriyatlari - bu sifatli ta'lim, amaliy ko'nikmalar va xalqaro imkoniyatlar",
    qualityEducation: "Sifatli ta'lim",
    qualityEducationDesc: "Eng yuqori sifatli ta'lim standartlariga rioya qilish",
    practicalSkills: "Amaliy ko'nikmalar",
    practicalSkillsDesc: "Haqiqiy IT loyihalarda qo'llaniladigan amaliy ko'nikmalarni o'rgatish",
    internationalOpportunities: "Xalqaro imkoniyatlar",
    internationalOpportunitiesDesc: "Xalqaro IT kompaniyalarda ishlash imkoniyatlarini yaratish",
    joinOurTeam: "Bizning jamoaga qo'shiling",
    joinTeamDescription: "IT English Academy jamoasiga qo'shiling va IT sohasida ingliz tilini o'rganing",

    // Contact page
    contactUsSubtitle: "Savollaringiz bormi? Biz bilan bog'laning",
    getInTouch: "Biz bilan bog'laning",
    contactDescription: "Savollaringiz bo'lsa yoki qo'shimcha ma'lumot olishni istasangiz, biz bilan bog'laning",
    addressValue: "Toshkent sh., Yunusobod tumani, 4-mavze",
    sendMessage: "Xabar yuborish",
    sendMessageDesc: "Bizga xabar yuboring va biz siz bilan tez orada bog'lanamiz",
    fullName: "To'liq ism",
    fullNamePlaceholder: "To'liq ismingizni kiriting",
    emailPlaceholder: "Elektron pochtangizni kiriting",
    phonePlaceholder: "Telefon raqamingizni kiriting",
    message: "Xabar",
    messagePlaceholder: "Xabaringizni kiriting",
    send: "Yuborish",
    sending: "Yuborilmoqda...",
    messageSent: "Xabar yuborildi",
    messageSentDesc: "Xabaringiz muvaffaqiyatli yuborildi. Tez orada siz bilan bog'lanamiz.",
    ourLocation: "Bizning manzil",
    visitOffice: "Ofisimizga tashrif buyuring",

    // Courses page
    itEnglishCourses: "IT ingliz tili kurslari",
    specializedEnglishCourses: "IT mutaxassislari uchun maxsus ingliz tili kurslari",
    searchCourses: "Kurslarni qidirish",
    level: "Daraja",
    allLevels: "Barcha darajalar",
    beginner: "Boshlang'ich",
    intermediate: "O'rta",
    advanced: "Yuqori",
    duration: "Davomiyligi",
    allDurations: "Barcha davomiyliklar",
    shortDuration: "Qisqa (4 haftagacha)",
    mediumDuration: "O'rta (4-8 hafta)",
    longDuration: "Uzoq (8 haftadan ortiq)",
    search: "Qidirish",
    availableCourses: "Mavjud kurslar",
    filter: "Filtrlash",
    loading: "Yuklanmoqda...",
    lessons: "Darslar",
    count: "ta",
    rating: "Reyting",
    currency: "so'm",
    viewCourse: "Kursni ko'rish",
    noCoursesFound: "Kurslar topilmadi",
    loadingCourseData: "Kurs ma'lumotlari yuklanmoqda...",
    courseNotFound: "Kurs topilmadi",
    courseNotFoundDescription: "Kechirasiz, siz qidirayotgan kurs topilmadi",
    backToAllCourses: "Barcha kurslarga qaytish",
    aboutCourse: "Kurs haqida",
    whatYouWillLearn: "Nimalarni o'rganasiz",
    syllabus: "O'quv dasturi",
    instructor: "O'qituvchi",
    chat: "Chat",
    week: "Hafta",
    instructorBio: "IT va ingliz tili sohasida tajribali o'qituvchi",
    watchTrialLesson: "Sinov darsini ko'rish",
    trialLesson: "Sinov darsi",
    trialLessonDescription: "Bu kursning sinov darsi. Kursni sotib olishdan oldin tanishib chiqishingiz mumkin.",
    tenMinutes: "10 daqiqa",

    // Authentication
    usernameAndPasswordRequired: "Foydalanuvchi nomi va parol talab qilinadi",
    loginSuccess: "Kirish muvaffaqiyatli",
    adminPanelOpening: "Admin panel ochilmoqda...",
    loginSuccessful: "Kirish muvaffaqiyatli amalga oshirildi",
    usernameOrPasswordIncorrect: "Foydalanuvchi nomi yoki parol noto'g'ri",
    error: "Xatolik",
    loginError: "Kirishda xatolik yuz berdi",
    enterYourCredentials: "Ma'lumotlaringizni kiriting",
    username: "Foydalanuvchi nomi",
    usernamePlaceholder: "Foydalanuvchi nomingizni kiriting",
    password: "Parol",
    forgotPassword: "Parolni unutdingizmi?",
    loggingIn: "Kirish...",
    noAccount: "Hisobingiz yo'qmi?",
    fillAllFields: "Barcha maydonlarni to'ldiring",
    passwordsDoNotMatch: "Parollar mos kelmaydi",
    success: "Muvaffaqiyat",
    registrationSuccessful: "Ro'yxatdan o'tish muvaffaqiyatli amalga oshirildi",
    registrationError: "Ro'yxatdan o'tishda xatolik yuz berdi",
    enterYourInformation: "Ma'lumotlaringizni kiriting",
    firstName: "Ism",
    firstNamePlaceholder: "Ismingizni kiriting",
    lastName: "Familiya",
    lastNamePlaceholder: "Familiyangizni kiriting",
    confirmPassword: "Parolni tasdiqlang",
    registering: "Ro'yxatdan o'tish...",
    alreadyHaveAccount: "Hisobingiz bormi?",

    // Jobs
    jobListings: "Ish o'rinlari",
    findYourDreamJob: "O'z orzuingizdagi ishni toping",
    searchJobs: "Ish o'rinlarini qidirish",
    jobTitle: "Ish nomi",
    location: "Joylashuv",
    jobType: "Ish turi",
    allLocations: "Barcha joylar",
    allJobTypes: "Barcha ish turlari",
    fullTime: "To'liq stavka",
    partTime: "Yarim stavka",
    remote: "Masofaviy",
    contract: "Shartnoma asosida",
    searchJobsButton: "Qidirish",
    latestJobs: "So'nggi ish o'rinlari",
    noJobsFound: "Ish o'rinlari topilmadi",
    applyNow: "Hozir ariza topshiring",
    jobDetails: "Ish tafsilotlari",
    aboutCompany: "Kompaniya haqida",
    jobDescription: "Ish tavsifi",
    requirements: "Talablar",
    benefits: "Imtiyozlar",
    salary: "Maosh",
    postedOn: "E'lon qilingan sana",
    applicationDeadline: "Ariza topshirish muddati",
    applyForThisJob: "Bu ish uchun ariza topshiring",
    jobApplication: "Ish uchun ariza",
    jobApplicationDescription: "Quyidagi formani to'ldiring va rezyumeingizni yuklang",
    coverLetter: "Yo'llanma xat",
    coverLetterPlaceholder: "Yo'llanma xatingizni kiriting",
    resume: "Rezyume",
    uploadResume: "Rezyume yuklash",
    resumeRequirements: "PDF, DOC yoki DOCX formatida, maksimal hajmi 5MB",
    submitApplication: "Arizani yuborish",
    submittingApplication: "Ariza yuborilmoqda...",
    applicationSubmitted: "Ariza yuborildi",
    applicationSubmittedDescription: "Arizangiz muvaffaqiyatli yuborildi. Tez orada siz bilan bog'lanamiz.",
    backToJobs: "Ish o'rinlariga qaytish",

    // Loading states
    loadingProfile: "Profil yuklanmoqda...",
    loadingCourses: "Kurslar yuklanmoqda...",
    loadingJobs: "Ish o'rinlari yuklanmoqda...",
    loadingCertificates: "Sertifikatlar yuklanmoqda...",
    loadingSettings: "Sozlamalar yuklanmoqda...",
    loadingChat: "Chat yuklanmoqda...",

    // Error messages
    somethingWentWrong: "Nimadir xato ketdi",
    tryAgainLater: "Keyinroq qayta urinib ko'ring",
    pageNotFound: "Sahifa topilmadi",
    pageNotFoundDescription: "Kechirasiz, siz qidirayotgan sahifa topilmadi",
    backToHomepage: "Bosh sahifaga qaytish",

    // Misc
    readMore: "Ko'proq o'qish",
    showMore: "Ko'proq ko'rsatish",
    showLess: "Kamroq ko'rsatish",
    apply: "Ariza topshirish",
    cancel: "Bekor qilish",
    save: "Saqlash",
    delete: "O'chirish",
    edit: "Tahrirlash",
    update: "Yangilash",
    confirm: "Tasdiqlash",
    close: "Yopish",
    yes: "Ha",
    no: "Yo'q",
    or: "yoki",
    and: "va",
    all: "Barchasi",
    none: "Hech biri",
    more: "Ko'proq",
    less: "Kamroq",
    back: "Orqaga",
    next: "Keyingi",
    previous: "Oldingi",
    continue: "Davom etish",
    finish: "Tugatish",
    start: "Boshlash",
    submit: "Yuborish",
    reset: "Qayta o'rnatish",
    clear: "Tozalash",
    add: "Qo'shish",
    remove: "Olib tashlash",
    create: "Yaratish",
    view: "Ko'rish",
    download: "Yuklab olish",
    upload: "Yuklash",
    share: "Ulashish",
    copy: "Nusxalash",
    paste: "Qo'yish",
    cut: "Kesish",
    select: "Tanlash",
    selectAll: "Barchasini tanlash",
    deselectAll: "Barchasini bekor qilish",
    today: "Bugun",
    yesterday: "Kecha",
    tomorrow: "Ertaga",
    now: "Hozir",
    date: "Sana",
    time: "Vaqt",
    day: "Kun",
    week: "Hafta",
    month: "Oy",
    year: "Yil",
    hour: "Soat",
    minute: "Daqiqa",
    second: "Soniya",
    name: "Ism",
    description: "Tavsif",
    title: "Sarlavha",
    category: "Kategoriya",
    type: "Tur",
    status: "Holat",
    active: "Faol",
    inactive: "Faol emas",
    pending: "Kutilmoqda",
    completed: "Tugatilgan",
    cancelled: "Bekor qilingan",
    approved: "Tasdiqlangan",
    rejected: "Rad etilgan",
    draft: "Qoralama",
    published: "E'lon qilingan",
    unpublished: "E'lon qilinmagan",
    public: "Ommaviy",
    private: "Shaxsiy",
    visible: "Ko'rinadigan",
    hidden: "Yashirin",
    enabled: "Yoqilgan",
    disabled: "O'chirilgan",
    locked: "Qulflangan",
    unlocked: "Qulflanmagan",
    required: "Talab qilinadi",
    optional: "Ixtiyoriy",
    default: "Standart",
    custom: "Maxsus",
    new: "Yangi",
    old: "Eski",
    recent: "So'nggi",
    popular: "Mashhur",
    trending: "Trend",
    featured: "Tavsiya etilgan",
    recommended: "Tavsiya etilgan",
    related: "Bog'liq",
    similar: "O'xshash",
    other: "Boshqa",
    more_info: "Ko'proq ma'lumot",
    learn_more: "Ko'proq o'rganish",
    help: "Yordam",
    support: "Qo'llab-quvvatlash",
    contact_support: "Qo'llab-quvvatlash xizmati bilan bog'lanish",
    faq: "Ko'p so'raladigan savollar",
    terms: "Foydalanish shartlari",
    privacy: "Maxfiylik siyosati",
    cookies: "Kukilar siyosati",
    copyright: "Mualliflik huquqi",
    rights_reserved: "Barcha huquqlar himoyalangan",
    menu: "Menyu",
    navigation: "Navigatsiya",
    dashboard: "Boshqaruv paneli",
    account: "Hisob",
    settings: "Sozlamalar",
    preferences: "Afzalliklar",
    notifications: "Bildirishnomalar",
    messages: "Xabarlar",
    inbox: "Kiruvchi xabarlar",
    sent: "Yuborilgan",
    drafts: "Qoralamalar",
    trash: "Chiqindi",
    archive: "Arxiv",
    starred: "Yulduzchali",
    important: "Muhim",
    flagged: "Belgilangan",
    spam: "Spam",
    junk: "Keraksiz",
    folder: "Papka",
    tag: "Teg",
    label: "Yorliq",
    category: "Kategoriya",
    group: "Guruh",
    list: "Ro'yxat",
    grid: "Setka",
    table: "Jadval",
    card: "Karta",
    board: "Doska",
    timeline: "Vaqt chizig'i",
    calendar: "Kalendar",
    gallery: "Galereya",
    slideshow: "Slayd-shou",
    carousel: "Karusel",
    player: "Pleyer",
    viewer: "Ko'rish dasturi",
    editor: "Muharrir",
    preview: "Oldindan ko'rish",
    print: "Chop etish",
    export: "Eksport",
    import: "Import",
    backup: "Zaxira nusxa",
    restore: "Tiklash",
    sync: "Sinxronlash",
    refresh: "Yangilash",
    reload: "Qayta yuklash",
    restart: "Qayta ishga tushirish",
    shutdown: "O'chirish",
    power: "Quvvat",
    sleep: "Uyqu rejimi",
    wake: "Uyg'onish",
    lock: "Qulflash",
    unlock: "Qulfdan chiqarish",
    secure: "Himoyalash",
    protect: "Himoya qilish",
    encrypt: "Shifrlash",
    decrypt: "Deshifrlash",
    verify: "Tekshirish",
    validate: "Tasdiqlash",
    check: "Tekshirish",
    test: "Sinov",
    debug: "Nosozliklarni tuzatish",
    fix: "Tuzatish",
    repair: "Ta'mirlash",
    maintain: "Texnik xizmat ko'rsatish",
    upgrade: "Yangilash",
    downgrade: "Pasaytirish",
    install: "O'rnatish",
    uninstall: "O'chirib tashlash",
    setup: "O'rnatish",
    configure: "Sozlash",
    customize: "Moslashtirish",
    personalize: "Shaxsiylashtirish",
    theme: "Mavzu",
    style: "Uslub",
    layout: "Tartib",
    design: "Dizayn",
    appearance: "Ko'rinish",
    behavior: "Xatti-harakat",
    performance: "Ishlash",
    speed: "Tezlik",
    efficiency: "Samaradorlik",
    optimization: "Optimallashtirish",
    improvement: "Yaxshilash",
    enhancement: "Kuchaytirish",
    feature: "Xususiyat",
    functionality: "Funksionallik",
    capability: "Imkoniyat",
    capacity: "Sig'im",
    limit: "Cheklov",
    restriction: "Cheklash",
    constraint: "Cheklov",
    requirement: "Talab",
    specification: "Spetsifikatsiya",
    standard: "Standart",
    guideline: "Ko'rsatma",
    rule: "Qoida",
    policy: "Siyosat",
    procedure: "Protsedura",
    process: "Jarayon",
    workflow: "Ish oqimi",
    pipeline: "Quvur",
    stream: "Oqim",
    flow: "Oqim",
    sequence: "Ketma-ketlik",
    order: "Tartib",
    sort: "Saralash",
    filter: "Filtrlash",
    search: "Qidirish",
    find: "Topish",
    locate: "Joylashuvini aniqlash",
    navigate: "Navigatsiya qilish",
    browse: "Ko'rib chiqish",
    explore: "O'rganish",
    discover: "Kashf qilish",
    learn: "O'rganish",
    study: "O'qish",
    practice: "Amaliyot",
    exercise: "Mashq",
    train: "Mashq qilish",
    develop: "Rivojlantirish",
    grow: "O'sish",
    expand: "Kengaytirish",
    extend: "Uzaytirish",
    increase: "Ko'paytirish",
    decrease: "Kamaytirish",
    reduce: "Qisqartirish",
    minimize: "Minimallashtirish",
    maximize: "Maksimallashtirish",
    optimize: "Optimallashtirish",
    itemRemoved: "Mahsulot olib tashlandi",
    itemRemovedFromCart: "Mahsulot savatchangizdan olib tashlandi",
    addedToCart: "Savatga qo'shildi",
    courseAddedToCart: "Kurs savatchangizga qo'shildi",
    failedToAddToCart: "Kursni savatga qo'shib bo'lmadi",
    pleaseEnterAllCardDetails: "Iltimos, barcha karta ma'lumotlarini kiriting",
    pleaseEnterValidSMSCode: "Iltimos, to'g'ri SMS kodni kiriting",
    userNotAuthenticated: "Foydalanuvchi autentifikatsiya qilinmagan",
    paymentProcessingError: "To'lovni amalga oshirishda xatolik",
    jobIsActive: "Ish e'loni faol",

    // Profile courses page
    noActiveCourses: "Sizda hozircha faol kurslar yo'q",
    noCompletedCourses: "Sizda hozircha tugatilgan kurslar yo'q",
    continueLearning: "O'rganishni davom ettirish",
    viewCertificate: "Sertifikatni ko'rish",
    aboutCourse: "Kurs haqida",

    // Cart page
    shoppingCart: "Savatcha",
    cartEmpty: "Savatchangiz bo'sh",
    browseCoursesToAddToCart: "Savatchangizga qo'shish uchun kurslarni ko'rib chiqing",
  },
  ru: {
    // Add these new translations
    accountInactive: "Ваш аккаунт неактивен",
    accountInactiveDescription: "Ваш аккаунт был удален или приостановлен администратором",
    loginFailed: "Ошибка входа",
    invalidEmailFormat: "Неверный формат электронной почты",
    invalidPhoneFormat: "Неверный формат номера телефона",
    usernameAlreadyExists: "Такое имя пользователя уже существует",
    // Navigation
    home: "Главная",
    courses: "Курсы",
    jobs: "Вакансии",
    about: "О нас",
    contact: "Контакты",
    login: "Вход",
    register: "Регистрация",
    profile: "Профиль",
    logout: "Выход",
    my_courses: "Мои курсы",
    cart: "Корзина",
    search: "Поиск",
    notifications: "Уведомления",
    mark_all_as_read: "Отметить все как прочитанные",
    no_notifications: "Нет уведомлений",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Темная",
    system: "Системная",
    adminPanel: "Админ панель",

    // Profile
    welcome_back: "С возвращением",
    welcome_message: "С возвращением, {name}",
    profile_completion: "Заполнение профиля",
    student: "Студент",
    english_b2: "Английский B2",
    it_beginner: "IT начинающий",
    edit_profile: "Редактировать профиль",
    quick_links: "Быстрые ссылки",
    certificates: "Сертификаты",
    support_chat: "Чат поддержки",
    browse_courses: "Просмотр курсов",
    overview: "Обзор",
    progress: "Прогресс",
    achievements: "Достижения",
    active_courses: "Активные курсы",
    completed_courses: "Завершенные курсы",
    next_lesson: "Следующий урок",
    join_now: "Присоединиться сейчас",
    recent_activity: "Недавняя активность",
    view_all_activity: "Просмотреть всю активность",
    learning_progress: "Прогресс обучения",
    progress_description: "Отслеживайте свой прогресс по всем курсам",
    your_achievements: "Ваши достижения",
    achievements_description: "Достижения, которые вы заработали",
    first_course: "Первый курс",
    completed_first_course: "Завершили свой первый курс",
    coding_streak: "Серия кодирования",
    seven_day_streak: "Поддерживали 7-дневную серию обучения",
    quiz_master: "Мастер викторин",
    perfect_score: "Получили идеальный результат на викторине",
    fast_learner: "Быстрый ученик",
    completed_course_quickly: "Завершили курс в рекордно короткие сроки",
    completed_lesson: "Завершен урок",
    days_ago: "дней назад",

    // Settings page
    settings: "Настройки",
    "manage account settings": "Управление настройками аккаунта",
    "profile information": "Информация профиля",
    "update profile information": "Обновить информацию профиля",
    "change avatar": "Изменить аватар",
    "remove avatar": "Удалить аватар",
    "first name": "Имя",
    "last name": "Фамилия",
    bio: "Биография",
    "tell us about yourself": "Расскажите о себе",
    "preferred language": "Предпочитаемый язык",
    "select language": "Выберите язык",
    cancel: "Отмена",
    "save changes": "Сохранить изменения",
    "account settings": "Настройки аккаунта",
    "update account settings": "Обновить настройки аккаунта",
    email: "Электронная почта",
    "change password": "Изменить пароль",
    "current password": "Текущий пароль",
    "new password": "Новый пароль",
    "confirm password": "Подтвердите пароль",
    "danger zone": "Опасная зона",
    "danger zone description": "Эти действия необратимы и полностью удалят ваш аккаунт",
    "delete account": "Удалить аккаунт",
    "notification settings": "Настройки уведомлений",
    "manage notification preferences": "Управление предпочтениями уведомлений",
    "email notifications": "Уведомления по электронной почте",
    "receive email notifications": "Получать уведомления по электронной почте",
    "push notifications": "Push-уведомления",
    "receive push notifications": "Получать push-уведомления",
    "marketing emails": "Маркетинговые письма",
    "receive marketing emails": "Получать маркетинговые письма",
    "course updates": "Обновления курсов",
    "receive course updates": "Получать обновления курсов",
    "lesson reminders": "Напоминания об уроках",
    "receive lesson reminders": "Получать напоминания об уроках",
    loading: "Загрузка...",

    // Homepage
    learnEnglishForIT: "Изучайте английский для IT",
    academyDescription: "IT English Academy - специализированные курсы английского языка для IT-специалистов",
    viewCourses: "Просмотр курсов",
    contactUs: "Связаться с нами",
    academyImageAlt: "Студенты IT English Academy",
    ourAdvantages: "Наши преимущества",
    whyChooseUs: "Почему выбирают нас",
    itEnglish: "IT английский",
    itEnglishDescription: "Курсы английского языка, специально разработанные для IT-сферы",
    modernTeaching: "Современное обучение",
    modernTeachingDescription: "Использование новейших методик и технологий обучения",
    experiencedTeachers: "Опытные преподаватели",
    experiencedTeachersDescription: "Преподаватели с опытом работы в IT и английском языке",
    practicalExercises: "Практические упражнения",
    practicalExercisesDescription: "Практические упражнения, применяемые в реальных IT-проектах",
    smallGroups: "Малые группы",
    smallGroupsDescription: "Малые группы для индивидуального подхода к каждому студенту",
    guaranteedResult: "Гарантированный результат",
    guaranteedResultDescription: "Гарантированный результат после завершения курса",
    popularCourses: "Популярные курсы",
    explorePopularCourses: "Ознакомьтесь с нашими самыми популярными курсами",
    englishBasics: "Основы английского",
    englishBasicsDescription: "Основы английского языка, необходимые для работы в IT-сфере",
    webDevelopment: "Веб-разработка",
    webDevelopmentDescription: "Основы веб-разработки и чтение технической документации на английском",
    price1: "800 000 сум",
    price2: "1 200 000 сум",
    price3: "1 500 000 сум",
    details: "Подробнее",
    registerNow: "Зарегистрируйтесь сейчас",
    registerNowDescription: "Зарегистрируйтесь на наши курсы и начните изучать английский для IT",
    register: "Регистрация",
    pages: "Страницы",
    address: "г. Ташкент, Юнусабадский район, 4-квартал",
    phone: "+998 90 123 45 67",
    email: "info@itenglish.academy",
    socialMedia: "Социальные сети",
    allRightsReserved: "Все права защищены",

    // About page
    backToHome: "Вернуться на главную",
    aboutHeroText: "IT English Academy - специализированные курсы английского языка для IT-специалистов",
    ourMission: "Наша миссия",
    missionText1:
      "IT English Academy - это учебный центр, специализирующийся на обучении английскому языку, необходимому для работы в IT-сфере.",
    missionText2:
      "Наша цель - повысить конкурентоспособность IT-специалистов на международном уровне через обучение английскому языку.",
    students: "Студенты",
    qualifiedTeachers: "Квалифицированные преподаватели",
    yearsExperience: "Лет опыта",
    ourTeam: "Наша команда",
    teamDescription: "Команда IT English Academy - это опытные специалисты в области IT и английского языка",
    headTeacher: "Главный преподаватель",
    itDepartmentHead: "Руководитель IT-отдела",
    academicDepartmentHead: "Руководитель учебного отдела",
    azizaBio:
      "Имеет 10-летний опыт преподавания английского языка. Специалист по обучению английскому языку в IT-сфере.",
    boburBio: "Имеет 5-летний опыт работы в IT-сфере. Full-stack разработчик и преподаватель.",
    malikaBio: "Имеет 8-летний опыт разработки учебных программ. Методист образования.",
    ourValues: "Наши ценности",
    valuesDescription:
      "Ценности IT English Academy - это качественное образование, практические навыки и международные возможности",
    qualityEducation: "Качественное образование",
    qualityEducationDesc: "Соблюдение самых высоких стандартов качества образования",
    practicalSkills: "Практические навыки",
    practicalSkillsDesc: "Обучение практическим навыкам, применяемым в реальных IT-проектах",
    internationalOpportunities: "Международные возможности",
    internationalOpportunitiesDesc: "Создание возможностей для работы в международных IT-компаниях",
    joinOurTeam: "Присоединяйтесь к нашей команде",
    joinTeamDescription: "Присоединяйтесь к команде IT English Academy и изучайте английский для IT",

    // Contact page
    contactUsSubtitle: "Есть вопросы? Свяжитесь с нами",
    getInTouch: "Свяжитесь с нами",
    contactDescription: "Если у вас есть вопросы или вы хотите получить дополнительную информацию, свяжитесь с нами",
    addressValue: "г. Ташкент, Юнусабадский район, 4-квартал",
    sendMessage: "Отправить сообщение",
    sendMessageDesc: "Отправьте нам сообщение, и мы свяжемся с вами в ближайшее время",
    fullName: "Полное имя",
    fullNamePlaceholder: "Введите ваше полное имя",
    emailPlaceholder: "Введите ваш email",
    phonePlaceholder: "Введите ваш номер телефона",
    message: "Сообщение",
    messagePlaceholder: "Введите ваше сообщение",
    send: "Отправить",
    sending: "Отправка...",
    messageSent: "Сообщение отправлено",
    messageSentDesc: "Ваше сообщение успешно отправлено. Мы свяжемся с вами в ближайшее время.",
    ourLocation: "Наше местоположение",
    visitOffice: "Посетите наш офис",

    // Courses page
    itEnglishCourses: "Курсы английского для IT",
    specializedEnglishCourses: "Специализированные курсы английского языка для IT-специалистов",
    searchCourses: "Поиск курсов",
    level: "Уровень",
    allLevels: "Все уровни",
    beginner: "Начальный",
    intermediate: "Средний",
    advanced: "Продвинутый",
    duration: "Продолжительность",
    allDurations: "Все продолжительности",
    shortDuration: "Короткие (до 4 недель)",
    mediumDuration: "Средние (4-8 недель)",
    longDuration: "Длинные (более 8 недель)",
    search: "Поиск",
    availableCourses: "Доступные курсы",
    filter: "Фильтр",
    loading: "Загрузка...",
    lessons: "Уроки",
    count: "",
    rating: "Рейтинг",
    currency: "сум",
    viewCourse: "Просмотр курса",
    noCoursesFound: "Курсы не найдены",
    loadingCourseData: "Загрузка данных курса...",
    courseNotFound: "Курс не найден",
    courseNotFoundDescription: "Извините, искомый вами курс не найден",
    backToAllCourses: "Вернуться ко всем курсам",
    aboutCourse: "О курсе",
    whatYouWillLearn: "Чему вы научитесь",
    syllabus: "Учебный план",
    instructor: "Преподаватель",
    chat: "Чат",
    week: "Неделя",
    instructorBio: "Опытный преподаватель в области IT и английского языка",
    watchTrialLesson: "Посмотреть пробный урок",
    trialLesson: "Пробный урок",
    trialLessonDescription: "Это пробный урок курса. Вы можете ознакомиться с ним перед покупкой курса.",
    tenMinutes: "10 минут",

    // Authentication
    usernameAndPasswordRequired: "Требуются имя пользователя и пароль",
    loginSuccess: "Вход выполнен успешно",
    adminPanelOpening: "Открывается панель администратора...",
    loginSuccessful: "Вход выполнен успешно",
    usernameOrPasswordIncorrect: "Неверное имя пользователя или пароль",
    error: "Ошибка",
    loginError: "Ошибка при входе",
    enterYourCredentials: "Введите ваши учетные данные",
    username: "Имя пользователя",
    usernamePlaceholder: "Введите имя пользователя",
    password: "Пароль",
    forgotPassword: "Забыли пароль?",
    loggingIn: "Вход...",
    noAccount: "Нет аккаунта?",
    fillAllFields: "Заполните все поля",
    passwordsDoNotMatch: "Пароли не совпадают",
    success: "Успех",
    registrationSuccessful: "Регистрация выполнена успешно",
    registrationError: "Ошибка при регистрации",
    enterYourInformation: "Введите вашу информацию",
    firstName: "Имя",
    firstNamePlaceholder: "Введите ваше имя",
    lastName: "Фамилия",
    lastNamePlaceholder: "Введите вашу фамилию",
    confirmPassword: "Подтвердите пароль",
    registering: "Регистрация...",
    alreadyHaveAccount: "Уже есть аккаунт?",

    // Jobs
    jobListings: "Вакансии",
    findYourDreamJob: "Найдите работу своей мечты",
    searchJobs: "Поиск вакансий",
    jobTitle: "Название должности",
    location: "Местоположение",
    jobType: "Тип работы",
    allLocations: "Все местоположения",
    allJobTypes: "Все типы работы",
    fullTime: "Полная занятость",
    partTime: "Частичная занятость",
    remote: "Удаленная работа",
    contract: "Контрактная работа",
    searchJobsButton: "Поиск",
    latestJobs: "Последние вакансии",
    noJobsFound: "Вакансии не найдены",
    applyNow: "Подать заявку сейчас",
    jobDetails: "Детали вакансии",
    aboutCompany: "О компании",
    jobDescription: "Описание работы",
    requirements: "Требования",
    benefits: "Преимущества",
    salary: "Зарплата",
    postedOn: "Дата публикации",
    applicationDeadline: "Срок подачи заявок",
    applyForThisJob: "Подать заявку на эту вакансию",
    jobApplication: "Заявка на вакансию",
    jobApplicationDescription: "Заполните форму ниже и загрузите свое резюме",
    coverLetter: "Сопроводительное письмо",
    coverLetterPlaceholder: "Введите ваше сопроводительное письмо",
    resume: "Резюме",
    uploadResume: "Загрузить резюме",
    resumeRequirements: "PDF, DOC или DOCX формат, максимальный размер 5MB",
    submitApplication: "Отправить заявку",
    submittingApplication: "Отправка заявки...",
    applicationSubmitted: "Заявка отправлена",
    applicationSubmittedDescription: "Ваша заявка успешно отправлена. Мы свяжемся с вами в ближайшее время.",
    backToJobs: "Вернуться к вакансиям",

    // Loading states
    loadingProfile: "Загрузка профиля...",
    loadingCourses: "Загрузка курсов...",
    loadingJobs: "Загрузка вакансий...",
    loadingCertificates: "Загрузка сертификатов...",
    loadingSettings: "Загрузка настроек...",
    loadingChat: "Загрузка чата...",

    // Error messages
    somethingWentWrong: "Что-то пошло не так",
    tryAgainLater: "Попробуйте позже",
    pageNotFound: "Страница не найдена",
    pageNotFoundDescription: "Извините, искомая вами страница не найдена",
    backToHomepage: "Вернуться на главную",

    // Misc
    readMore: "Читать далее",
    showMore: "Показать больше",
    showLess: "Показать меньше",
    apply: "Подать заявку",
    cancel: "Отмена",
    save: "Сохранить",
    delete: "Удалить",
    edit: "Редактировать",
    update: "Обновить",
    confirm: "Подтвердить",
    close: "Закрыть",
    yes: "Да",
    no: "Нет",
    or: "или",
    and: "и",
    all: "Все",
    none: "Ничего",
    more: "Больше",
    less: "Меньше",
    back: "Назад",
    next: "Далее",
    previous: "Предыдущий",
    continue: "Продолжить",
    finish: "Завершить",
    start: "Начать",
    submit: "Отправить",
    reset: "Сбросить",
    clear: "Очистить",
    add: "Добавить",
    remove: "Удалить",
    create: "Создать",
    view: "Просмотр",
    download: "Скачать",
    upload: "Загрузить",
    share: "Поделиться",
    copy: "Копировать",
    paste: "Вставить",
    cut: "Вырезать",
    select: "Выбрать",
    selectAll: "Выбрать все",
    deselectAll: "Отменить выбор всех",
    today: "Сегодня",
    yesterday: "Вчера",
    tomorrow: "Завтра",
    now: "Сейчас",
    date: "Дата",
    time: "Время",
    day: "День",
    week: "Неделя",
    month: "Месяц",
    year: "Год",
    hour: "Час",
    minute: "Минута",
    second: "Секунда",
    name: "Имя",
    description: "Описание",
    title: "Заголовок",
    category: "Категория",
    type: "Тип",
    status: "Статус",
    active: "Активный",
    inactive: "Неактивный",
    pending: "В ожидании",
    completed: "Завершено",
    cancelled: "Отменено",
    approved: "Одобрено",
    rejected: "Отклонено",
    draft: "Черновик",
    published: "Опубликовано",
    unpublished: "Не опубликовано",
    public: "Публичный",
    private: "Приватный",
    visible: "Видимый",
    hidden: "Скрытый",
    enabled: "Включено",
    disabled: "Отключено",
    locked: "Заблокировано",
    unlocked: "Разблокировано",
    required: "Обязательно",
    optional: "Необязательно",
    default: "По умолчанию",
    custom: "Пользовательский",
    new: "Новый",
    old: "Старый",
    recent: "Недавний",
    popular: "Популярный",
    trending: "В тренде",
    featured: "Рекомендуемый",
    recommended: "Рекомендуемый",
    related: "Связанный",
    similar: "Похожий",
    other: "Другой",
    more_info: "Больше информации",
    learn_more: "Узнать больше",
    help: "Помощь",
    support: "Поддержка",
    contact_support: "Связаться с поддержкой",
    faq: "Часто задаваемые вопросы",
    terms: "Условия использования",
    privacy: "Политика конфиденциальности",
    cookies: "Политика использования файлов cookie",
    copyright: "Авторское право",
    rights_reserved: "Все права защищены",
    menu: "Меню",
    navigation: "Навигация",
    dashboard: "Панель управления",
    account: "Аккаунт",
    settings: "Настройки",
    preferences: "Предпочтения",
    notifications: "Уведомления",
    messages: "Сообщения",
    inbox: "Входящие",
    sent: "Отправленные",
    drafts: "Черновики",
    trash: "Корзина",
    archive: "Архив",
    starred: "Помеченные",
    important: "Важные",
    flagged: "Отмеченные",
    spam: "Спам",
    junk: "Нежелательные",
    folder: "Папка",
    tag: "Тег",
    label: "Метка",
    category: "Категория",
    group: "Группа",
    list: "Список",
    grid: "Сетка",
    table: "Таблица",
    card: "Карточка",
    board: "Доска",
    timeline: "Временная шкала",
    calendar: "Календарь",
    gallery: "Галерея",
    slideshow: "Слайд-шоу",
    carousel: "Карусель",
    player: "Плеер",
    viewer: "Просмотрщик",
    editor: "Редактор",
    preview: "Предпросмотр",
    print: "Печать",
    export: "Экспорт",
    import: "Импорт",
    backup: "Резервное копирование",
    restore: "Восстановление",
    sync: "Синхронизация",
    refresh: "Обновить",
    reload: "Перезагрузить",
    restart: "Перезапустить",
    shutdown: "Выключение",
    power: "Питание",
    sleep: "Спящий режим",
    wake: "Пробуждение",
    lock: "Блокировка",
    unlock: "Разблокировка",
    secure: "Защитить",
    protect: "Защитить",
    encrypt: "Шифровать",
    decrypt: "Дешифровать",
    verify: "Проверить",
    validate: "Подтвердить",
    check: "Проверить",
    test: "Тест",
    debug: "Отладка",
    fix: "Исправить",
    repair: "Ремонт",
    maintain: "Обслуживание",
    upgrade: "Обновление",
    downgrade: "Понижение версии",
    install: "Установить",
    uninstall: "Удалить",
    setup: "Настройка",
    configure: "Настроить",
    customize: "Настроить",
    personalize: "Персонализировать",
    theme: "Тема",
    style: "Стиль",
    layout: "Макет",
    design: "Дизайн",
    appearance: "Внешний вид",
    behavior: "Поведение",
    performance: "Производительность",
    speed: "Скорость",
    efficiency: "Эффективность",
    optimization: "Оптимизация",
    improvement: "Улучшение",
    enhancement: "Улучшение",
    feature: "Функция",
    functionality: "Функциональность",
    capability: "Возможность",
    capacity: "Емкость",
    limit: "Лимит",
    restriction: "Ограничение",
    constraint: "Ограничение",
    requirement: "Требование",
    specification: "Спецификация",
    standard: "Стандарт",
    guideline: "Руководство",
    rule: "Правило",
    policy: "Политика",
    procedure: "Процедура",
    process: "Процесс",
    workflow: "Рабочий процесс",
    pipeline: "Конвейер",
    stream: "Поток",
    flow: "Поток",
    sequence: "Последовательность",
    order: "Порядок",
    sort: "Сортировка",
    filter: "Фильтр",
    search: "Поиск",
    find: "Найти",
    locate: "Найти местоположение",
    navigate: "Навигация",
    browse: "Просмотр",
    explore: "Исследовать",
    discover: "Обнаружить",
    learn: "Изучить",
    study: "Изучать",
    practice: "Практика",
    exercise: "Упражнение",
    train: "Тренировка",
    develop: "Развивать",
    grow: "Расти",
    expand: "Расширять",
    extend: "Расширять",
    increase: "Увеличивать",
    decrease: "Уменьшать",
    reduce: "Сокращать",
    minimize: "Минимизировать",
    maximize: "Максимизировать",
    optimize: "Оптимизировать",
    itemRemoved: "Товар удален",
    itemRemovedFromCart: "Товар был удален из вашей корзины",
    addedToCart: "Добавлено в корзину",
    courseAddedToCart: "Курс был добавлен в вашу корзину",
    failedToAddToCart: "Не удалось добавить курс в корзину",
    pleaseEnterAllCardDetails: "Пожалуйста, введите все данные карты",
    pleaseEnterValidSMSCode: "Пожалуйста, введите действительный SMS-код",
    userNotAuthenticated: "Пользователь не аутентифицирован",
    paymentProcessingError: "Ошибка обработки платежа",
    jobIsActive: "Вакансия активна",

    // Profile courses page
    noActiveCourses: "У вас пока нет активных курсов",
    noCompletedCourses: "У вас пока нет завершенных курсов",
    continueLearning: "Продолжить обучение",
    viewCertificate: "Посмотреть сертификат",
    aboutCourse: "О курсе",

    // Cart page
    shoppingCart: "Корзина",
    cartEmpty: "Ваша корзина пуста",
    browseCoursesToAddToCart: "Просмотрите курсы, чтобы добавить их в корзину",
  },
  en: {
    // Add these new translations
    accountInactive: "Your account is inactive",
    accountInactiveDescription: "Your account has been deleted or suspended by the administrator",
    loginFailed: "Login Failed",
    invalidEmailFormat: "Invalid email format",
    invalidPhoneFormat: "Invalid phone number format",
    usernameAlreadyExists: "Username already exists",
    // Navigation
    home: "Home",
    courses: "Courses",
    jobs: "Jobs",
    about: "About",
    contact: "Contact",
    login: "Login",
    register: "Register",
    profile: "Profile",
    logout: "Logout",
    my_courses: "My Courses",
    cart: "Cart",
    search: "Search",
    notifications: "Notifications",
    mark_all_as_read: "Mark all as read",
    no_notifications: "No notifications",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    adminPanel: "Admin Panel",

    // Profile
    welcome_back: "Welcome Back",
    welcome_message: "Welcome back, {name}",
    profile_completion: "Profile Completion",
    student: "Student",
    english_b2: "English B2",
    it_beginner: "IT Beginner",
    edit_profile: "Edit Profile",
    quick_links: "Quick Links",
    certificates: "Certificates",
    support_chat: "Support Chat",
    browse_courses: "Browse Courses",
    overview: "Overview",
    progress: "Progress",
    achievements: "Achievements",
    active_courses: "Active Courses",
    completed_courses: "Completed Courses",
    next_lesson: "Next Lesson",
    join_now: "Join Now",
    recent_activity: "Recent Activity",
    view_all_activity: "View All Activity",
    learning_progress: "Learning Progress",
    progress_description: "Track your progress across all courses",
    your_achievements: "Your Achievements",
    achievements_description: "Achievements you've earned so far",
    first_course: "First Course",
    completed_first_course: "Completed your first course",
    coding_streak: "Coding Streak",
    seven_day_streak: "Maintained a 7-day learning streak",
    quiz_master: "Quiz Master",
    perfect_score: "Achieved a perfect score on a quiz",
    fast_learner: "Fast Learner",
    completed_course_quickly: "Completed a course in record time",
    completed_lesson: "Completed Lesson",
    days_ago: "days ago",

    // Settings page
    settings: "Settings",
    "manage account settings": "Manage your account settings",
    "profile information": "Profile Information",
    "update profile information": "Update your profile information",
    "change avatar": "Change Avatar",
    "remove avatar": "Remove Avatar",
    "first name": "First Name",
    "last name": "Last Name",
    bio: "Bio",
    "tell us about yourself": "Tell us about yourself",
    "preferred language": "Preferred Language",
    "select language": "Select Language",
    cancel: "Cancel",
    "save changes": "Save Changes",
    "account settings": "Account Settings",
    "update account settings": "Update your account settings",
    email: "Email",
    "change password": "Change Password",
    "current password": "Current Password",
    "new password": "New Password",
    "confirm password": "Confirm Password",
    "danger zone": "Danger Zone",
    "danger zone description": "These actions are irreversible and will permanently delete your account",
    "delete account": "Delete Account",
    "notification settings": "Notification Settings",
    "manage notification preferences": "Manage your notification preferences",
    "email notifications": "Email Notifications",
    "receive email notifications": "Receive notifications via email",
    "push notifications": "Push Notifications",
    "receive push notifications": "Receive push notifications",
    "marketing emails": "Marketing Emails",
    "receive marketing emails": "Receive marketing emails",
    "course updates": "Course Updates",
    "receive course updates": "Receive course updates",
    "lesson reminders": "Lesson Reminders",
    "receive lesson reminders": "Receive lesson reminders",
    loading: "Loading...",

    // Homepage
    learnEnglishForIT: "Learn English for IT",
    academyDescription: "IT English Academy - specialized English courses for IT professionals",
    viewCourses: "View Courses",
    contactUs: "Contact Us",
    academyImageAlt: "IT English Academy students",
    ourAdvantages: "Our Advantages",
    whyChooseUs: "Why Choose Us",
    itEnglish: "IT English",
    itEnglishDescription: "English courses specifically designed for the IT field",
    modernTeaching: "Modern Teaching",
    modernTeachingDescription: "Using the latest teaching methods and technologies",
    experiencedTeachers: "Experienced Teachers",
    experiencedTeachersDescription: "Teachers with experience in IT and English language",
    practicalExercises: "Practical Exercises",
    practicalExercisesDescription: "Practical exercises used in real IT projects",
    smallGroups: "Small Groups",
    smallGroupsDescription: "Small groups for individual approach to each student",
    guaranteedResult: "Guaranteed Result",
    guaranteedResultDescription: "Guaranteed result after completing the course",
    popularCourses: "Popular Courses",
    explorePopularCourses: "Explore our most popular courses",
    englishBasics: "English Basics",
    englishBasicsDescription: "Basic English skills necessary for working in IT",
    webDevelopment: "Web Development",
    webDevelopmentDescription: "Web development basics and reading technical documentation in English",
    price1: "800,000 UZS",
    price2: "1,200,000 UZS",
    price3: "1,500,000 UZS",
    details: "Details",
    registerNow: "Register Now",
    registerNowDescription: "Register for our courses and start learning English for IT",
    register: "Register",
    pages: "Pages",
    address: "Tashkent, Yunusabad district, 4th quarter",
    phone: "+998 90 123 45 67",
    email: "info@itenglish.academy",
    socialMedia: "Social Media",
    allRightsReserved: "All rights reserved",

    // About page
    backToHome: "Back to Home",
    aboutHeroText: "IT English Academy - specialized English courses for IT professionals",
    ourMission: "Our Mission",
    missionText1:
      "IT English Academy is a learning center specializing in teaching English necessary for working in the IT field.",
    missionText2:
      "Our goal is to increase the competitiveness of IT professionals internationally through English language training.",
    students: "Students",
    qualifiedTeachers: "Qualified Teachers",
    yearsExperience: "Years Experience",
    ourTeam: "Our Team",
    teamDescription: "The IT English Academy team consists of experienced professionals in IT and English language",
    headTeacher: "Head Teacher",
    itDepartmentHead: "IT Department Head",
    academicDepartmentHead: "Academic Department Head",
    azizaBio: "Has 10 years of experience teaching English. Specialist in teaching English for the IT field.",
    boburBio: "Has 5 years of experience working in IT. Full-stack developer and teacher.",
    malikaBio: "Has 8 years of experience developing educational programs. Education methodologist.",
    ourValues: "Our Values",
    valuesDescription:
      "IT English Academy values - quality education, practical skills, and international opportunities",
    qualityEducation: "Quality Education",
    qualityEducationDesc: "Adhering to the highest quality education standards",
    practicalSkills: "Practical Skills",
    practicalSkillsDesc: "Teaching practical skills used in real IT projects",
    internationalOpportunities: "International Opportunities",
    internationalOpportunitiesDesc: "Creating opportunities to work in international IT companies",
    joinOurTeam: "Join Our Team",
    joinTeamDescription: "Join the IT English Academy team and learn English for IT",

    // Contact page
    contactUsSubtitle: "Have questions? Contact us",
    getInTouch: "Get in Touch",
    contactDescription: "If you have questions or want additional information, contact us",
    addressValue: "Tashkent, Yunusabad district, 4th quarter",
    sendMessage: "Send Message",
    sendMessageDesc: "Send us a message and we will contact you soon",
    fullName: "Full Name",
    fullNamePlaceholder: "Enter your full name",
    emailPlaceholder: "Enter your email",
    phonePlaceholder: "Enter your phone number",
    message: "Message",
    messagePlaceholder: "Enter your message",
    send: "Send",
    sending: "Sending...",
    messageSent: "Message Sent",
    messageSentDesc: "Your message has been successfully sent. We will contact you soon.",
    ourLocation: "Our Location",
    visitOffice: "Visit our office",

    // Courses page
    itEnglishCourses: "IT English Courses",
    specializedEnglishCourses: "Specialized English courses for IT professionals",
    searchCourses: "Search Courses",
    level: "Level",
    allLevels: "All Levels",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    duration: "Duration",
    allDurations: "All Durations",
    shortDuration: "Short (up to 4 weeks)",
    mediumDuration: "Medium (4-8 weeks)",
    longDuration: "Long (more than 8 weeks)",
    search: "Search",
    availableCourses: "Available Courses",
    filter: "Filter",
    loading: "Loading...",
    lessons: "Lessons",
    count: "",
    rating: "Rating",
    currency: "UZS",
    viewCourse: "View Course",
    noCoursesFound: "No courses found",
    loadingCourseData: "Loading course data...",
    courseNotFound: "Course not found",
    courseNotFoundDescription: "Sorry, the course you are looking for was not found",
    backToAllCourses: "Back to all courses",
    aboutCourse: "About Course",
    whatYouWillLearn: "What You Will Learn",
    syllabus: "Syllabus",
    instructor: "Instructor",
    chat: "Chat",
    week: "Week",
    instructorBio: "Experienced teacher in IT and English language",
    watchTrialLesson: "Watch Trial Lesson",
    trialLesson: "Trial Lesson",
    trialLessonDescription: "This is a trial lesson for the course. You can check it out before purchasing the course.",
    tenMinutes: "10 minutes",

    // Authentication
    usernameAndPasswordRequired: "Username and password are required",
    loginSuccess: "Login Successful",
    adminPanelOpening: "Opening admin panel...",
    loginSuccessful: "Login successful",
    usernameOrPasswordIncorrect: "Username or password incorrect",
    error: "Error",
    loginError: "Error logging in",
    enterYourCredentials: "Enter your credentials",
    username: "Username",
    usernamePlaceholder: "Enter your username",
    password: "Password",
    forgotPassword: "Forgot password?",
    loggingIn: "Logging in...",
    noAccount: "Don't have an account?",
    fillAllFields: "Please fill all fields",
    passwordsDoNotMatch: "Passwords do not match",
    success: "Success",
    registrationSuccessful: "Registration successful",
    registrationError: "Error during registration",
    enterYourInformation: "Enter your information",
    firstName: "First Name",
    firstNamePlaceholder: "Enter your first name",
    lastName: "Last Name",
    lastNamePlaceholder: "Enter your last name",
    confirmPassword: "Confirm Password",
    registering: "Registering...",
    alreadyHaveAccount: "Already have an account?",

    // Jobs
    jobListings: "Job Listings",
    findYourDreamJob: "Find Your Dream Job",
    searchJobs: "Search Jobs",
    jobTitle: "Job Title",
    location: "Location",
    jobType: "Job Type",
    allLocations: "All Locations",
    allJobTypes: "All Job Types",
    fullTime: "Full Time",
    partTime: "Part Time",
    remote: "Remote",
    contract: "Contract",
    searchJobsButton: "Search",
    latestJobs: "Latest Jobs",
    noJobsFound: "No jobs found",
    applyNow: "Apply Now",
    jobDetails: "Job Details",
    aboutCompany: "About Company",
    jobDescription: "Job Description",
    requirements: "Requirements",
    benefits: "Benefits",
    salary: "Salary",
    postedOn: "Posted On",
    applicationDeadline: "Application Deadline",
    applyForThisJob: "Apply for this Job",
    jobApplication: "Job Application",
    jobApplicationDescription: "Fill out the form below and upload your resume",
    coverLetter: "Cover Letter",
    coverLetterPlaceholder: "Enter your cover letter",
    resume: "Resume",
    uploadResume: "Upload Resume",
    resumeRequirements: "PDF, DOC or DOCX format, max size 5MB",
    submitApplication: "Submit Application",
    submittingApplication: "Submitting application...",
    applicationSubmitted: "Application Submitted",
    applicationSubmittedDescription: "Your application has been successfully submitted. We will contact you soon.",
    backToJobs: "Back to Jobs",

    // Loading states
    loadingProfile: "Loading profile...",
    loadingCourses: "Loading courses...",
    loadingJobs: "Loading jobs...",
    loadingCertificates: "Loading certificates...",
    loadingSettings: "Loading settings...",
    loadingChat: "Loading chat...",

    // Error messages
    somethingWentWrong: "Something went wrong",
    tryAgainLater: "Please try again later",
    pageNotFound: "Page not found",
    pageNotFoundDescription: "Sorry, the page you are looking for was not found",
    backToHomepage: "Back to homepage",

    // Misc
    readMore: "Read More",
    showMore: "Show More",
    showLess: "Show Less",
    apply: "Apply",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    update: "Update",
    confirm: "Confirm",
    close: "Close",
    yes: "Yes",
    no: "No",
    or: "or",
    and: "and",
    all: "All",
    none: "None",
    more: "More",
    less: "Less",
    back: "Back",
    next: "Next",
    previous: "Previous",
    continue: "Continue",
    finish: "Finish",
    start: "Start",
    submit: "Submit",
    reset: "Reset",
    clear: "Clear",
    add: "Add",
    remove: "Remove",
    create: "Create",
    view: "View",
    download: "Download",
    upload: "Upload",
    share: "Share",
    copy: "Copy",
    paste: "Paste",
    cut: "Cut",
    select: "Select",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    now: "Now",
    date: "Date",
    time: "Time",
    day: "Day",
    week: "Week",
    month: "Month",
    year: "Year",
    hour: "Hour",
    minute: "Minute",
    second: "Second",
    name: "Name",
    description: "Description",
    title: "Title",
    category: "Category",
    type: "Type",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    approved: "Approved",
    rejected: "Rejected",
    draft: "Draft",
    published: "Published",
    unpublished: "Unpublished",
    public: "Public",
    private: "Private",
    visible: "Visible",
    hidden: "Hidden",
    enabled: "Enabled",
    disabled: "Disabled",
    locked: "Locked",
    unlocked: "Unlocked",
    required: "Required",
    optional: "Optional",
    default: "Default",
    custom: "Custom",
    new: "New",
    old: "Old",
    recent: "Recent",
    popular: "Popular",
    trending: "Trending",
    featured: "Featured",
    recommended: "Recommended",
    related: "Related",
    similar: "Similar",
    other: "Other",
    more_info: "More Info",
    learn_more: "Learn More",
    help: "Help",
    support: "Support",
    contact_support: "Contact Support",
    faq: "FAQ",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    cookies: "Cookie Policy",
    copyright: "Copyright",
    rights_reserved: "All rights reserved",
    menu: "Menu",
    navigation: "Navigation",
    dashboard: "Dashboard",
    account: "Account",
    settings: "Settings",
    preferences: "Preferences",
    notifications: "Notifications",
    messages: "Messages",
    inbox: "Inbox",
    sent: "Sent",
    drafts: "Drafts",
    trash: "Trash",
    archive: "Archive",
    starred: "Starred",
    important: "Important",
    flagged: "Flagged",
    spam: "Spam",
    junk: "Junk",
    folder: "Folder",
    tag: "Tag",
    label: "Label",
    category: "Category",
    group: "Group",
    list: "List",
    grid: "Grid",
    table: "Table",
    card: "Card",
    board: "Board",
    timeline: "Timeline",
    calendar: "Calendar",
    gallery: "Gallery",
    slideshow: "Slideshow",
    carousel: "Carousel",
    player: "Player",
    viewer: "Viewer",
    editor: "Editor",
    preview: "Preview",
    print: "Print",
    export: "Export",
    import: "Import",
    backup: "Backup",
    restore: "Restore",
    sync: "Sync",
    refresh: "Refresh",
    reload: "Reload",
    restart: "Restart",
    shutdown: "Shutdown",
    power: "Power",
    sleep: "Sleep",
    wake: "Wake",
    lock: "Lock",
    unlock: "Unlock",
    secure: "Secure",
    protect: "Protect",
    encrypt: "Encrypt",
    decrypt: "Decrypt",
    verify: "Verify",
    validate: "Validate",
    check: "Check",
    test: "Test",
    debug: "Debug",
    fix: "Fix",
    repair: "Repair",
    maintain: "Maintain",
    upgrade: "Upgrade",
    downgrade: "Downgrade",
    install: "Install",
    uninstall: "Uninstall",
    setup: "Setup",
    configure: "Configure",
    customize: "Customize",
    personalize: "Personalize",
    theme: "Theme",
    style: "Style",
    layout: "Layout",
    design: "Design",
    appearance: "Appearance",
    behavior: "Behavior",
    performance: "Performance",
    speed: "Speed",
    efficiency: "Efficiency",
    optimization: "Optimization",
    improvement: "Improvement",
    enhancement: "Enhancement",
    feature: "Feature",
    functionality: "Functionality",
    capability: "Capability",
    capacity: "Capacity",
    limit: "Limit",
    restriction: "Restriction",
    constraint: "Constraint",
    requirement: "Requirement",
    specification: "Specification",
    standard: "Standard",
    guideline: "Guideline",
    rule: "Rule",
    policy: "Policy",
    procedure: "Procedure",
    process: "Process",
    workflow: "Workflow",
    pipeline: "Pipeline",
    stream: "Stream",
    flow: "Flow",
    sequence: "Sequence",
    order: "Order",
    sort: "Sort",
    filter: "Filter",
    search: "Search",
    find: "Find",
    locate: "Locate",
    navigate: "Navigate",
    browse: "Browse",
    explore: "Explore",
    discover: "Discover",
    learn: "Learn",
    study: "Study",
    practice: "Practice",
    exercise: "Exercise",
    train: "Train",
    develop: "Develop",
    grow: "Grow",
    expand: "Expand",
    extend: "Extend",
    increase: "Increase",
    decrease: "Decrease",
    reduce: "Reduce",
    minimize: "Minimize",
    maximize: "Maximize",
    optimize: "Optimize",
    itemRemoved: "Item Removed",
    itemRemovedFromCart: "Item has been removed from your cart",
    addedToCart: "Added to Cart",
    courseAddedToCart: "Course has been added to your cart",
    failedToAddToCart: "Failed to add course to cart",
    pleaseEnterAllCardDetails: "Please enter all card details",
    pleaseEnterValidSMSCode: "Please enter a valid SMS code",
    userNotAuthenticated: "User not authenticated",
    paymentProcessingError: "Error processing payment",
    jobIsActive: "Job listing is active",

    // Profile courses page
    noActiveCourses: "You don't have any active courses yet",
    noCompletedCourses: "You don't have any completed courses yet",
    continueLearning: "Continue Learning",
    viewCertificate: "View Certificate",
    aboutCourse: "About Course",

    // Cart page
    shoppingCart: "Shopping Cart",
    cartEmpty: "Your cart is empty",
    browseCoursesToAddToCart: "Browse courses to add them to your cart",
  },
}

// Create language context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Language provider component
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const router = useRouter()
  const pathname = usePathname()
  const [language, setLanguageState] = useState<Language>("uz")
  const [translations, setTranslations] = useState<Translations>(defaultTranslations)
  const [mounted, setMounted] = useState(false)

  // Initialize language from localStorage
  useEffect(() => {
    setMounted(true)
    const savedLanguage = localStorage.getItem("language")
    if (savedLanguage && ["uz", "ru", "en"].includes(savedLanguage)) {
      setLanguageState(savedLanguage as Language)
    }

    // Create a custom event for language changes
    const handleLanguageEvent = (e: CustomEvent) => {
      if (e.detail && ["uz", "ru", "en"].includes(e.detail)) {
        setLanguageState(e.detail as Language)
      }
    }

    // Add event listener for language changes
    window.addEventListener("languageChanged" as any, handleLanguageEvent)

    return () => {
      window.removeEventListener("languageChanged" as any, handleLanguageEvent)
    }
  }, [])

  // Add this function after the setLanguage function
  const notifyLanguageChange = useCallback((lang: Language) => {
    // Create a custom event for language changes that all components can listen to
    if (typeof window !== "undefined") {
      const event = new CustomEvent("languageChanged", { detail: lang })
      window.dispatchEvent(event)
    }
  }, [])

  // Set language and save to localStorage
  const setLanguage = useCallback(
    (lang: Language) => {
      setLanguageState(lang)
      localStorage.setItem("language", lang)

      // Notify other components about the language change
      notifyLanguageChange(lang)

      // Update HTML lang attribute
      document.documentElement.lang = lang
    },
    [notifyLanguageChange],
  )

  // Translation function
  const t = useCallback(
    (key: string, params?: Record<string, string>): string => {
      if (!mounted) return key

      let text = translations[language]?.[key] || key

      // Replace parameters if provided
      if (params) {
        Object.entries(params).forEach(([paramKey, paramValue]) => {
          text = text.replace(`{${paramKey}}`, paramValue)
        })
      }

      return text
    },
    [language, translations, mounted],
  )

  // Set global language variable for non-React components
  useEffect(() => {
    if (mounted && typeof window !== "undefined") {
      window.__GLOBAL_LANGUAGE = {
        current: language,
        t: (key: string, params?: Record<string, string>) => {
          let text = translations[language]?.[key] || key

          // Replace parameters if provided
          if (params) {
            Object.entries(params).forEach(([paramKey, paramValue]) => {
              text = text.replace(`{${paramKey}}`, paramValue)
            })
          }

          return text
        },
      }

      // Update HTML lang attribute
      document.documentElement.lang = language
    }
  }, [language, translations, mounted])

  // Context value
  const value = {
    language,
    setLanguage,
    t,
    translations,
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

// Custom hook to use language context
export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    // If context is undefined, try to use global language
    if (typeof window !== "undefined" && window.__GLOBAL_LANGUAGE) {
      return {
        language: window.__GLOBAL_LANGUAGE.current as Language,
        setLanguage: (lang: Language) => {
          localStorage.setItem("language", lang)
          window.__GLOBAL_LANGUAGE.current = lang
          // Dispatch custom event
          const event = new CustomEvent("languageChanged", { detail: lang })
          window.dispatchEvent(event)
          // Update HTML lang attribute
          document.documentElement.lang = lang
        },
        t: (key: string, params?: Record<string, string>) => window.__GLOBAL_LANGUAGE.t(key, params) || key,
        translations: defaultTranslations,
      }
    }
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

// Declare global window interface
declare global {
  interface Window {
    __GLOBAL_LANGUAGE: {
      current: string
      t: (key: string, params?: Record<string, string>) => string
    }
  }
}

